#include "Ast/TypeDefLangAst.h"
#include "CodeGenerators/CppMirTypeTableGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

namespace CodeGenerators
{

namespace
{
struct GeneratedTypeEntry
{
    std::string m_name;
    uint32_t m_bitWidth{ 0 };
    uint32_t m_alignment{ 0 };
    DSL::Ast::TypeDef::TypeKind m_kind{ DSL::Ast::TypeDef::TypeKind::Integer };
    std::string m_fieldName;
    std::string m_getterName;
    uint8_t m_compactId{ 0 };
};

std::string KindToEnumString(DSL::Ast::TypeDef::TypeKind kind)
{
    switch (kind)
    {
        case DSL::Ast::TypeDef::TypeKind::Void:
            return "MirTypeKind::Void";
        case DSL::Ast::TypeDef::TypeKind::Integer:
            return "MirTypeKind::Integer";
        case DSL::Ast::TypeDef::TypeKind::FloatingPoint:
            return "MirTypeKind::FloatingPoint";
        case DSL::Ast::TypeDef::TypeKind::BindingToken:
            return "MirTypeKind::BindingToken";
        case DSL::Ast::TypeDef::TypeKind::Pointer:
            return "MirTypeKind::Pointer";
    }
    return "MirTypeKind::Integer";
}

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                // Unmodified content: preserve mtime to prevent unnecessary rebuild cascades
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

void EmitHeader(std::ostream &out, const std::vector<GeneratedTypeEntry> &types)
{
    out << R"(#ifndef EZMIR_MIR_TYPE_TABLE_H
#define EZMIR_MIR_TYPE_TABLE_H

// Auto-generated by EzDSL CppMirTypeTableGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include "Type/MirType.h"

#include <array>

/**
 * Compact machine type identifiers for dense LUT indexing during legalization / ISel.
 */
enum class MirTypeCompactId : uint8_t
{
    Invalid = 0,
)";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    {} = {},\n", type.m_name, type.m_compactId);
    }

    out << R"(    Custom = 255
};

/**
 * Total number of machine-defined primitive types.
 */
constexpr size_t MachineTypeCount = )"
        << types.size() << R"(;

/**
 * Class used to store the least minimum required types so everything else works.
 */
class MirTypeTable
{
  public:
    static constexpr uint8_t InvalidCompactId = 0;
    static constexpr uint8_t CustomCompactId = 255;
    static constexpr size_t MachineDefinedTypeCount = )"
        << types.size() << R"(;

    /**
     * Creates the type table with the given arena allocator.
     */
    explicit MirTypeTable(std::pmr::memory_resource *globalArena, size_t pointerBitWidth = 64);

    // Disable copies to safeguard our arena resource mappings
    MirTypeTable(const MirTypeTable &) = delete;
    MirTypeTable &operator=(const MirTypeTable &) = delete;

    /**
     * Creates a unique base or compound type.
     */
    MirType *create(MirTypeKind kind,
                    size_t totalSizeInBits,
                    size_t totalAlignmentInBits,
                    std::pmr::vector<MirType *> subTypes,
                    const std::string_view &name,
                    uint8_t compactId = CustomCompactId);

    /**
     * Creates a function type with the given parameters. This function will CREATE only if it wasn't added before, if
     * it was the existing type is returned.
     */
    MirType *getFuncType(MirType *returnType,
                         const std::pmr::list<class MirRegister *> &parameters,
                         const std::string_view &funcName);

    /**
     * Interns pointer types. Guarantees that getPtr(T) always returns the exact same type instance pointer.
     */
    MirType *getPtr(MirType *srcType);

    /**
     * Interns array types structurally based on size and base element composition.
     */
    MirType *getArray(MirType *elementType, size_t elementCount);

    /**
     * Returns the first floating-point type that can hold the given bit size.
     */
    MirType *getFloatingTypeBySize(size_t sizeInBits) const;

    /**
     * Returns the first integer type that can hold the given bit size.
     */
    MirType *getIntegerTypeBySize(size_t sizeInBits) const;

    /**
     * Searches the table for the given ID and returns its type, if any. Returns nullptr if type was not created.
     */
    MirType *getMirTypeById(size_t id) const;

    /**
     * Fast O(1) array lookup using dense compact machine type IDs for legalization and ISel tables.
     */
    MirType *getTypeByCompactId(uint8_t compactId) const;

    /**
     * Returns the target pointer width in bits.
     */
    size_t getPointerBitWidth() const { return m_pointerBitWidth; }

    /**
     * Returns the total number of unique types instantiated in this table.
     */
    size_t getTypeCount() const;

    // --- Built-in & Generated Type Accessors ---
)";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    MirType *{}();\n", type.m_getterName);
    }

    out << R"(
    /**
     * Initializes the type table with the basic primitive types using the given pointer size.
     */
    void initialize(size_t pointerBitWidth);

  private:
    size_t m_currentId{ 0 };
    size_t m_pointerBitWidth{ 64 };

    // Built-in & Generated Primitives
)";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    MirType *{}{{ nullptr }};\n", type.m_fieldName);
    }

    out << R"(
    std::pmr::memory_resource *m_arena;

    // Dense lookup cache mapping compactId to primitive MirType instance
    std::array<MirType *, 256> m_compactIdToType{};

    // High performance tracking hashes using PMR mapping blocks
    std::pmr::unordered_map<std::pmr::string, MirType *> m_typeNames;
    std::pmr::unordered_map<size_t, MirType *> m_idToType;

    // Interning caches: maps base type to its unique pointer type representation
    std::pmr::unordered_map<MirType *, MirType *> m_pointerCache;
};

#endif // EZMIR_MIR_TYPE_TABLE_H
)";
}

void EmitSource(std::ostream &out, const std::vector<GeneratedTypeEntry> &types)
{
    out << R"code(// Auto-generated by EzDSL CppMirTypeTableGenerator. DO NOT EDIT.

#include "Type/MirTypeTable.h"
#include "Operand/MirOperands.h"

MirTypeTable::MirTypeTable(std::pmr::memory_resource *globalArena, size_t pointerBitWidth) :
    m_pointerBitWidth(pointerBitWidth),
    m_arena(globalArena),
    m_typeNames(globalArena),
    m_idToType(globalArena),
    m_pointerCache(globalArena)
{
    m_compactIdToType.fill(nullptr);
}

MirType *MirTypeTable::create(MirTypeKind kind,
                              size_t totalSizeInBits,
                              size_t totalAlignmentInBits,
                              std::pmr::vector<MirType *> subTypes,
                              const std::string_view &name,
                              uint8_t compactId)
{
    if (name.empty())
    {
        return nullptr;
    }

    std::pmr::string lookupName(name, m_arena);
    auto it = m_typeNames.find(lookupName);
    if (it != m_typeNames.end())
    {
        return it->second;
    }

    size_t assignedId = ++m_currentId;

    std::pmr::polymorphic_allocator<MirType> alloc(m_arena);
    MirType *uniqueType = alloc.new_object<MirType>(kind,
                                                    this,
                                                    assignedId,
                                                    totalAlignmentInBits,
                                                    totalSizeInBits,
                                                    lookupName,
                                                    std::move(subTypes),
                                                    compactId);

    m_typeNames[lookupName] = uniqueType;
    m_idToType[assignedId] = uniqueType;

    if (compactId != CustomCompactId && compactId != InvalidCompactId)
    {
        m_compactIdToType[compactId] = uniqueType;
    }

    return uniqueType;
}

MirType *MirTypeTable::getFuncType(MirType *returnType,
                                   const std::pmr::list<MirRegister *> &parameters,
                                   const std::string_view &funcName)
{
    if (!returnType)
    {
        return nullptr;
    }

    auto structuralSignature = returnType->getName();
    structuralSignature += "(";

    std::pmr::vector<MirType *> subTypes(m_arena);
    subTypes.reserve(parameters.size() + 1);
    subTypes.push_back(returnType);

    for (auto &param : parameters)
    {
        if (!param)
            continue;
        MirType *paramType = param->getMirType();
        subTypes.push_back(paramType);

        if (subTypes.size() > 2)
        {
            structuralSignature += ",";
        }
        structuralSignature += paramType->getName();
    }
    structuralSignature += ")";

    std::pmr::string lookupKey(structuralSignature, m_arena);
    auto it = m_typeNames.find(lookupKey);
    if (it != m_typeNames.end())
    {
        return it->second;
    }

    return create(MirTypeKind::Function, m_pointerBitWidth, m_pointerBitWidth, std::move(subTypes), lookupKey, CustomCompactId);
}

MirType *MirTypeTable::getPtr(MirType *srcType)
{
    if (!srcType)
        return nullptr;

    auto it = m_pointerCache.find(srcType);
    if (it != m_pointerCache.end())
    {
        return it->second;
    }

    std::pmr::vector<MirType *> childTarget({ srcType }, m_arena);
    std::string formattedName = std::format("{}*", srcType->getName());

    MirType *newPointerType =
            create(MirTypeKind::Pointer, m_pointerBitWidth, m_pointerBitWidth, std::move(childTarget), formattedName, CustomCompactId);

    m_pointerCache[srcType] = newPointerType;
    return newPointerType;
}

MirType *MirTypeTable::getArray(MirType *elementType, size_t elementCount)
{
    if (!elementType)
        return nullptr;

    std::string arraySignature = std::format("{}[{}]", elementType->getName(), elementCount);
    std::pmr::string lookupName(arraySignature, m_arena);

    auto it = m_typeNames.find(lookupName);
    if (it != m_typeNames.end())
    {
        return it->second;
    }

    size_t totalSizeInBits = elementType->getTotalSizeInBits() * elementCount;
    size_t alignmentInBits = elementType->getMaxAlignmentInBits();
    std::pmr::vector<MirType *> childType({ elementType }, m_arena);

    return create(MirTypeKind::Array, totalSizeInBits, alignmentInBits, std::move(childType), lookupName, CustomCompactId);
}

MirType *MirTypeTable::getFloatingTypeBySize(size_t sizeInBits) const
{
    MirType *result = nullptr;
    for (auto &[id, type] : m_idToType)
    {
        if (type->getKind() != MirTypeKind::FloatingPoint)
            continue;

        size_t typeSize = type->getTotalSizeInBits();
        if (typeSize >= sizeInBits)
        {
            if (!result || typeSize < result->getTotalSizeInBits())
            {
                result = type;
            }
        }
    }
    return result;
}

MirType *MirTypeTable::getIntegerTypeBySize(size_t sizeInBits) const
{
    MirType *result = nullptr;
    for (auto &[id, type] : m_idToType)
    {
        if (type->getKind() != MirTypeKind::Integer)
            continue;

        size_t typeSize = type->getTotalSizeInBits();
        if (typeSize >= sizeInBits)
        {
            if (!result || typeSize < result->getTotalSizeInBits())
            {
                result = type;
            }
        }
    }
    return result;
}

MirType *MirTypeTable::getMirTypeById(size_t id) const
{
    auto it = m_idToType.find(id);
    return (it != m_idToType.end()) ? it->second : nullptr;
}

MirType *MirTypeTable::getTypeByCompactId(uint8_t compactId) const
{
    return m_compactIdToType[compactId];
}

size_t MirTypeTable::getTypeCount() const
{
    return m_idToType.size();
}
)code";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("MirType *MirTypeTable::{}() {{ return {}; }}\n", type.m_getterName, type.m_fieldName);
    }

    out << R"(
void MirTypeTable::initialize(size_t pointerBitWidth)
{
    m_pointerBitWidth = pointerBitWidth;
)";
    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    {} = create({}, {}, {}, {{}}, \"{}\", {});\n",
                           type.m_fieldName,
                           KindToEnumString(type.m_kind),
                           type.m_bitWidth,
                           type.m_alignment,
                           type.m_name,
                           static_cast<uint32_t>(type.m_compactId));
    }

    out << "}\n";
}

} // namespace

bool GenerateMirTypeTable(DiagnosticCollector *collector,
                          SymbolTable *table,
                          std::filesystem::path outPath,
                          MirTypeTableGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::MirTypeTable";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate MirTypeTable with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating type table in {}", outPath.string());

    // 1. Collect all type declarations from the symbol table.
    std::vector<GeneratedTypeEntry> collectedTypes;
    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym || sym->getType() != SymbolType::Type)
        {
            continue;
        }

        const auto *data = sym->getIf<Sema::Symbols::TypeSymbol>();
        if (!data)
        {
            continue;
        }

        std::string typeName(sym->getName());

        collectedTypes.push_back(GeneratedTypeEntry{ .m_name = typeName,
                                                     .m_bitWidth = data->m_bitWidth,
                                                     .m_alignment = data->m_alignment,
                                                     .m_kind = data->m_kind,
                                                     .m_fieldName = std::format("m_{}Type", typeName),
                                                     .m_getterName = typeName,
                                                     .m_compactId = data->m_compactId });
    }

    // 2. Resolve destination file paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / "MirTypeTable.h";
        sourcePath = outPath / "MirTypeTable.cpp";
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
            if (ec)
            {
                collector->error(genName,
                                 "Failed to create directory {}: {}",
                                 outPath.parent_path().string(),
                                 ec.message());
                return false;
            }
        }

        if (outPath.extension() == ".h" || outPath.extension() == ".hpp")
        {
            headerPath = outPath;
            sourcePath = outPath;
            sourcePath.replace_extension(".cpp");
        }
        else
        {
            sourcePath = outPath;
            headerPath = outPath;
            headerPath.replace_extension(".h");
        }
    }

    // 3. Write Header if requested using WriteFileIfChanged
    if (mode & MirTypeTableGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, collectedTypes);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    // 4. Write Source if requested using WriteFileIfChanged
    if (mode & MirTypeTableGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, collectedTypes);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName, "Successfully generated {} type definitions", collectedTypes.size());

    return true;
}

} // namespace CodeGenerators