#include "parser/grammar/TokenType.h"

namespace grammar
{
std::shared_ptr<ParseRule> tokenType(IRTokenType type)
{
    return ParseRule::create(
        [type](IParser &parser, const std::shared_ptr<Ast> &out) -> bool {
            auto &token = parser.peek();
            if (!parser.consumeIfToken(type))
            {
                parser.logParserError(LogMessage("").add("Expected {} but got {}", g_IRTokenTypeStr[type],
                                                         g_IRTokenTypeStr[token.m_type]),
                                      token);
                return false;
            }

            /*
             * Since we didn't use .map directive in the rule, children generated by this rule will be pushed to out,
             * discarding the TokenTypeNode created for this rule. Look at ParseRule::matchRet.
             *
             * Extra information: out->addChild will push to the parent TokenTypeNode, and since we didn't specify .map,
             * parent TokenTypeNode's children will be pushed to its parent.
             */

            if (token.m_type == IRTokenType::Identifier || token.m_type == IRTokenType::String ||
                token.m_type == IRTokenType::NumberFloat || token.m_type == IRTokenType::NumberInt)
            {
                std::shared_ptr<TokenTypeNode> node = std::make_shared<TokenTypeNode>();
                node->setTokenType(token.m_type);
                node->setContent(token.m_str);

                out->addChild(node);
            }

            return true;
        },
        "tokenType");
}
} // namespace Grammar
