#include "CodeGenerators/CppCallingConvGenerator.h"
#include "Ast/CallingConvDefLangAst.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace CodeGenerators
{

namespace
{

struct CallingConvEntry
{
    std::string m_name;
    uint32_t m_stackAlign{ 16 };
    uint32_t m_shadowSpace{ 0 };
    bool m_growsDown{ true };
    bool m_calleeCleanup{ false };
};

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

void EmitHeader(std::ostream &out,
                std::string_view targetName,
                const std::vector<CallingConvEntry> &convs)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_CALLING_CONVENTIONS_H
#define EZDSL_{0}_CALLING_CONVENTIONS_H

// Auto-generated by EzDSL CppCallingConvGenerator. DO NOT EDIT.

#include "Function/CallingConvDesc.h"
#include <memory_resource>
#include <vector>

namespace {1}
{{

)",
                       targetUpper,
                       targetName);

    for (const auto &cc : convs)
    {
        out << std::format(R"(/**
 * Calling convention descriptor for {0}.
 */
class {0}_CallingConvDesc : public CallingConvDesc
{{
  public:
    explicit {0}_CallingConvDesc(std::pmr::memory_resource *alloc) :
        m_alloc(alloc),
        m_calleeSaved(alloc),
        m_callerSaved(alloc)
    {{}}

    ~{0}_CallingConvDesc() override = default;

    ArgumentLocationDesc getArgLoc(MirType *type, CallLoweringState *callState) override;
    ArgumentLocationDesc getReturnLoc(MirType *type, CallLoweringState *callState) override;
    bool canReturnInRegs(MirType *type) const override;
    bool isCalleeCleanup() const override;
    bool doesStackGrowsDownwards() const override;
    const char *getName() const override;
    MirRegisterRef getFramePointerReg() const override;
    MirRegisterRef getStackPointerReg() const override;
    size_t getStackAlignment() const override;
    size_t getShadowSpaceSize() const override;
    bool hasFramePointer(MirFunction *func) const override;
    void classify(MirType *type, std::pmr::vector<CallingConvTypeClass> &out) const override;
    const std::pmr::vector<MirRegisterRef> &getAllCalleeSavedRegs() override;
    const std::pmr::vector<MirRegisterRef> &getCalleeSavedRegs(MirRegisterClass *_class) override;
    const std::pmr::vector<MirRegisterRef> &getAllCallerSavedRegs() override;
    const std::pmr::vector<MirRegisterRef> &getCallerSavedRegs(MirRegisterClass *_class) override;

  private:
    std::pmr::memory_resource *m_alloc;
    std::pmr::vector<MirRegisterRef> m_calleeSaved;
    std::pmr::vector<MirRegisterRef> m_callerSaved;
}};

CallingConvDesc *Create_{0}(std::pmr::memory_resource *alloc);

)",
                           cc.m_name);
    }

    out << std::format(R"(/**
 * Factory function creating all available calling conventions for {0}.
 */
std::pmr::vector<CallingConvDesc *> CreateAllCallingConventions(std::pmr::memory_resource *alloc);

}} // namespace {0}

#endif // EZDSL_{1}_CALLING_CONVENTIONS_H
)",
                       targetName,
                       targetUpper);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<CallingConvEntry> &convs)
{
    out << std::format(R"(// Auto-generated by EzDSL CppCallingConvGenerator. DO NOT EDIT.

#include "{0}"

namespace {1}
{{

)",
                       headerFileName,
                       targetName);

    for (const auto &cc : convs)
    {
        out << std::format(R"(ArgumentLocationDesc {0}_CallingConvDesc::getArgLoc(MirType *type, CallLoweringState *callState)
{{
    (void)type;
    (void)callState;
    return ArgumentLocationDesc{{}};
}}

ArgumentLocationDesc {0}_CallingConvDesc::getReturnLoc(MirType *type, CallLoweringState *callState)
{{
    (void)type;
    (void)callState;
    return ArgumentLocationDesc{{}};
}}

bool {0}_CallingConvDesc::canReturnInRegs(MirType *type) const
{{
    (void)type;
    return true;
}}

bool {0}_CallingConvDesc::isCalleeCleanup() const
{{
    return {1};
}}

bool {0}_CallingConvDesc::doesStackGrowsDownwards() const
{{
    return {2};
}}

const char *{0}_CallingConvDesc::getName() const
{{
    return "{0}";
}}

MirRegisterRef {0}_CallingConvDesc::getFramePointerReg() const
{{
    return MirRegisterRef{{}};
}}

MirRegisterRef {0}_CallingConvDesc::getStackPointerReg() const
{{
    return MirRegisterRef{{}};
}}

size_t {0}_CallingConvDesc::getStackAlignment() const
{{
    return {3};
}}

size_t {0}_CallingConvDesc::getShadowSpaceSize() const
{{
    return {4};
}}

bool {0}_CallingConvDesc::hasFramePointer(MirFunction *func) const
{{
    (void)func;
    return false;
}}

void {0}_CallingConvDesc::classify(MirType *type, std::pmr::vector<CallingConvTypeClass> &out) const
{{
    (void)type;
    out.push_back(CallingConvTypeClass::Integer);
}}

const std::pmr::vector<MirRegisterRef> &{0}_CallingConvDesc::getAllCalleeSavedRegs()
{{
    return m_calleeSaved;
}}

const std::pmr::vector<MirRegisterRef> &{0}_CallingConvDesc::getCalleeSavedRegs(MirRegisterClass *_class)
{{
    (void)_class;
    return m_calleeSaved;
}}

const std::pmr::vector<MirRegisterRef> &{0}_CallingConvDesc::getAllCallerSavedRegs()
{{
    return m_callerSaved;
}}

const std::pmr::vector<MirRegisterRef> &{0}_CallingConvDesc::getCallerSavedRegs(MirRegisterClass *_class)
{{
    (void)_class;
    return m_callerSaved;
}}

CallingConvDesc *Create_{0}(std::pmr::memory_resource *alloc)
{{
    std::pmr::polymorphic_allocator<{0}_CallingConvDesc> polyAlloc(alloc);
    return polyAlloc.new_object<{0}_CallingConvDesc>(alloc);
}}

)",
                           cc.m_name,
                           cc.m_calleeCleanup ? "true" : "false",
                           cc.m_growsDown ? "true" : "false",
                           cc.m_stackAlign,
                           cc.m_shadowSpace);
    }

    out << std::format(R"(std::pmr::vector<CallingConvDesc *> CreateAllCallingConventions(std::pmr::memory_resource *alloc)
{{
    std::pmr::vector<CallingConvDesc *> result(alloc);
)",
                       targetName);

    for (const auto &cc : convs)
    {
        out << std::format("    result.push_back(Create_{}(alloc));\n", cc.m_name);
    }

    out << std::format(R"(    return result;
}}

}} // namespace {0}
)",
                       targetName);
}

} // namespace

bool GenerateTargetCallingConventions(DiagnosticCollector *collector,
                                      SymbolTable *table,
                                      std::filesystem::path outPath,
                                      std::string_view targetName,
                                      CallingConvGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetCallingConventions";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetCallingConventions with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target calling conventions in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest Calling Conventions
    std::vector<CallingConvEntry> convs;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym) continue;

        if (sym->getType() == SymbolType::CallingConv)
        {
            const auto *data = sym->getIf<Sema::Symbols::CallingConvSymbol>();
            if (data)
            {
                CallingConvEntry entry;
                entry.m_name = std::string(sym->getName());
                entry.m_stackAlign = data->m_stackAlign;
                entry.m_shadowSpace = data->m_shadowSpace;
                entry.m_growsDown = (data->m_stackDirection == DSL::Ast::CallingConvDef::StackDirection::Down);
                entry.m_calleeCleanup = (data->m_stackCleanup == DSL::Ast::CallingConvDef::StackCleaner::Callee);
                convs.push_back(std::move(entry));
            }
        }
    }

    // 3. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}CallingConventions", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
    }

    std::string headerFileName = headerPath.filename().string();

    if (mode & CallingConvGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName, convs);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & CallingConvGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, convs);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized {} calling conventions into {}",
                     convs.size(),
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
