#include "CodeGenerators/CppISelTableGenerator.h"
#include "Ast/LegalizeRuleDefLangAst.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace CodeGenerators
{

namespace
{

struct PatternOperand
{
    std::string m_name;
    DSL::Ast::LegalizeRuleDef::OperandKind m_kind{ DSL::Ast::LegalizeRuleDef::OperandKind::SsaRegister };
};

struct PatternEmitInst
{
    std::string m_opcode;
    std::vector<std::string> m_operands;
};

struct PatternEntry
{
    std::string m_name;
    std::string m_matchOpcode;
    uint32_t m_cost{ 1 };
    std::vector<PatternOperand> m_matchOperands;
    std::vector<PatternEmitInst> m_emitInsts;
};

struct AddrModeEntry
{
    std::string m_name;
    size_t m_variantCount{ 0 };
};

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

void EmitHeader(std::ostream &out,
                std::string_view targetName,
                const std::vector<AddrModeEntry> &addrModes,
                const std::vector<PatternEntry> &patterns)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_ISEL_TABLE_H
#define EZDSL_{0}_ISEL_TABLE_H

// Auto-generated by EzDSL CppISelTableGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include "InstructionSelector/MirInstructionSelector.h"

class MirBuilderContext;
class MirInstruction;
class MirOperand;

namespace {1}
{{

// --- Addressing Mode Matchers ---
)",
                       targetUpper,
                       targetName);

    for (const auto &am : addrModes)
    {
        out << std::format("bool Match_AddrMode_{}(const MirOperand *addr);\n", am.m_name);
    }

    out << std::format(R"(
/**
 * High-performance decision tree instruction selector for {0}.
 */
class {0}InstructionSelector : public MirInstructionSelector
{{
  public:
    {0}InstructionSelector() = default;
    ~{0}InstructionSelector() override = default;

    /**
     * Selects and replaces generic MIR instructions with target hardware instructions.
     */
    bool select(MirBuilderContext *ctx, MirInstruction *inst) override;

  private:
)",
                       targetName);

    for (const auto &pat : patterns)
    {
        out << std::format("    static bool MatchAndSelect_{}(MirBuilderContext *ctx, MirInstruction *inst);\n",
                           pat.m_name);
    }

    out << std::format(R"(}};

}} // namespace {0}

#endif // EZDSL_{1}_ISEL_TABLE_H
)",
                       targetName,
                       targetUpper);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<AddrModeEntry> &addrModes,
                const std::vector<PatternEntry> &patterns)
{
    out << std::format(R"(// Auto-generated by EzDSL CppISelTableGenerator. DO NOT EDIT.

#include "{0}"
#include "{1}InstructionDefs.h"
#include "Block/MirBlock.h"
#include "Builder/MirBuilderContext.h"
#include "Instruction/MirInstruction.h"
#include "Instruction/MirInstructionBuilder.h"
#include "Instruction/MirTargetInstructionDesc.h"
#include "Operand/MirOperand.h"
#include "Operand/MirOperandBuilder.h"
#include "Operand/MirOperands.h"

namespace {1}
{{

)",
                       headerFileName,
                       targetName);

    for (const auto &am : addrModes)
    {
        out << std::format(R"(bool Match_AddrMode_{0}(const MirOperand *addr)
{{
    if (!addr) return false;
    return true;
}}

)",
                            am.m_name);
    }

    // Group patterns by match opcode and sort by cost ascending
    std::map<std::string, std::vector<PatternEntry>> groupedPatterns;
    for (const auto &pat : patterns)
    {
        groupedPatterns[pat.m_matchOpcode].push_back(pat);
    }
    for (auto &[opcode, plist] : groupedPatterns)
    {
        std::sort(plist.begin(), plist.end(), [](const PatternEntry &a, const PatternEntry &b) {
            return a.m_cost < b.m_cost;
        });
    }

    out << std::format(R"(bool {0}InstructionSelector::select(MirBuilderContext *ctx, MirInstruction *inst)
{{
    if (!ctx || !inst) return false;

    std::string_view op = inst->getMnemonic();

)",
                       targetName);

    // Optimized Decision Tree Dispatch
    for (const auto &[opcode, plist] : groupedPatterns)
    {
        if (!opcode.empty())
        {
            out << std::format("    if (op == \"{}\")\n    {{\n", opcode);
            for (const auto &pat : plist)
            {
                out << std::format("        if (MatchAndSelect_{}(ctx, inst)) return true;\n", pat.m_name);
            }
            out << "    }\n";
        }
        else
        {
            for (const auto &pat : plist)
            {
                out << std::format("    if (MatchAndSelect_{}(ctx, inst)) return true;\n", pat.m_name);
            }
        }
    }

    out << "    return false;\n}\n\n";

    for (const auto &pat : patterns)
    {
        out << std::format(R"(bool {0}InstructionSelector::MatchAndSelect_{1}(MirBuilderContext *ctx, MirInstruction *inst)
{{
    if (!ctx || !inst) return false;
    auto &operands = inst->getOperands();
)",
                           targetName,
                           pat.m_name);

        size_t expectedOps = pat.m_matchOperands.size();
        if (expectedOps > 0)
        {
            out << std::format("    if (operands.size() < {}) return false;\n", expectedOps);
        }

        for (size_t i = 0; i < expectedOps; ++i)
        {
            const auto &mOp = pat.m_matchOperands[i];
            if (mOp.m_kind == DSL::Ast::LegalizeRuleDef::OperandKind::SsaRegister)
            {
                out << std::format("    if (!operands[{0}] || !operands[{0}]->isOfType<MirRegister>()) return false;\n", i);
            }
            else if (mOp.m_kind == DSL::Ast::LegalizeRuleDef::OperandKind::ImmediateLiteral ||
                     mOp.m_kind == DSL::Ast::LegalizeRuleDef::OperandKind::ImmediateSymbol)
            {
                out << std::format("    if (!operands[{0}] || !operands[{0}]->isOfType<MirInteger>()) return false;\n", i);
            }
        }

        if (!pat.m_emitInsts.empty())
        {
            for (size_t k = 0; k < pat.m_emitInsts.size(); ++k)
            {
                const auto &emitInst = pat.m_emitInsts[k];
                out << std::format("    const auto *desc_{0} = GetTargetInstructionDesc(TargetOpCode::{1});\n", k, emitInst.m_opcode);
                out << std::format("    MirInstructionBuilder ib_{0}(ctx, inst->getOwner(), InsertionType::InsertBefore, inst);\n", k);
                out << std::format("    std::initializer_list<MirOperand *> emitOps_{0} = {{ ", k);

                bool first = true;
                for (const auto &emitOpName : emitInst.m_operands)
                {
                    if (!first) out << ", ";
                    first = false;

                    int foundIdx = -1;
                    for (size_t i = 0; i < pat.m_matchOperands.size(); ++i)
                    {
                        if (pat.m_matchOperands[i].m_name == emitOpName)
                        {
                            foundIdx = static_cast<int>(i);
                            break;
                        }
                    }
                    if (foundIdx >= 0)
                    {
                        out << std::format("operands[{}]", foundIdx);
                    }
                    else
                    {
                        out << "nullptr";
                    }
                }
                out << " };\n";
                out << std::format("    ib_{0}.buildTarget(const_cast<MirTargetInstructionDesc*>(desc_{0}), inst->getSourceRef(), emitOps_{0});\n", k);
            }

            out << std::format(R"(    inst->getOwner()->getInstructions().erase(
        std::find(inst->getOwner()->getInstructions().begin(), inst->getOwner()->getInstructions().end(), inst)
    );
    return true;
}}

)");
        }
        else
        {
            out << "    return false;\n}\n\n";
        }
    }

    out << std::format("}} // namespace {}\n", targetName);
}

} // namespace

bool GenerateTargetISelTable(DiagnosticCollector *collector,
                             SymbolTable *table,
                             std::filesystem::path outPath,
                             std::string_view targetName,
                             ISelTableGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetISelTable";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetISelTable with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target ISel table in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest ISel Patterns & AddrModes from SymbolTable
    std::vector<AddrModeEntry> addrModes;
    std::vector<PatternEntry> patterns;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym) continue;

        if (sym->getType() == SymbolType::AddrMode)
        {
            const auto *data = sym->getIf<Sema::Symbols::AddrModeSymbol>();
            if (data)
            {
                addrModes.push_back(AddrModeEntry{
                    .m_name = std::string(data->m_name),
                    .m_variantCount = data->m_variants.size()
                });
            }
        }
        else if (sym->getType() == SymbolType::ISelPattern)
        {
            const auto *data = sym->getIf<Sema::Symbols::ISelPatternSymbol>();
            if (data)
            {
                PatternEntry entry;
                entry.m_name = std::string(data->m_patternName);
                entry.m_cost = data->m_cost;
                if (!data->m_matchPatterns.empty())
                {
                    entry.m_matchOpcode = std::string(data->m_matchPatterns[0].m_opcode);
                    for (const auto &op : data->m_matchPatterns[0].m_operands)
                    {
                        entry.m_matchOperands.push_back(PatternOperand{
                            .m_name = std::string(op.m_name),
                            .m_kind = op.m_kind
                        });
                    }
                }
                for (const auto &emit : data->m_emitSequence)
                {
                    PatternEmitInst einstr;
                    einstr.m_opcode = std::string(emit.m_opcode);
                    for (const auto &op : emit.m_operands)
                    {
                        einstr.m_operands.push_back(std::string(op.m_name));
                    }
                    entry.m_emitInsts.push_back(std::move(einstr));
                }
                patterns.push_back(std::move(entry));
            }
        }
    }

    // 3. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}ISelTable", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
    }

    std::string headerFileName = headerPath.filename().string();

    if (mode & ISelTableGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName, addrModes, patterns);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & ISelTableGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, addrModes, patterns);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized {} ISel patterns and {} addressing modes into {}",
                     patterns.size(),
                     addrModes.size(),
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
