#include "CodeGenerators/CppLegalizerRuleGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace CodeGenerators
{

namespace
{

struct RuleEntry
{
    std::string m_name;
    std::string m_matchOpcode;
    size_t m_patternCount{ 0 };
    size_t m_expansionCount{ 0 };
};

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

void EmitHeader(std::ostream &out,
                std::string_view targetName,
                const std::vector<RuleEntry> &rules)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_LEGALIZE_RULES_H
#define EZDSL_{0}_LEGALIZE_RULES_H

// Auto-generated by EzDSL CppLegalizerRuleGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include "Legalizer/MirExpansionRuleRegistry.h"

class MirBuilderContext;
class MirInstruction;

namespace {1}
{{

/**
 * Concrete legalization expansion rule registry for {1}.
 * Implements high-throughput rewrite and expansion algorithms for illegal or multi-word operations.
 */
class {1}LegalizeRules : public MirExpansionRuleRegistry
{{
  public:
    {1}LegalizeRules() = default;
    ~{1}LegalizeRules() override = default;

    /**
     * Attempts to expand an illegal MIR instruction using synthesized rewrite rules.
     */
    bool tryExpand(MirBuilderContext *ctx, MirInstruction *inst) override;

  private:
)",
                       targetUpper,
                       targetName);

    for (const auto &rule : rules)
    {
        out << std::format("    static bool Expand_{}(MirBuilderContext *ctx, MirInstruction *inst);\n", rule.m_name);
    }

    out << std::format(R"(}};

}} // namespace {0}

#endif // EZDSL_{1}_LEGALIZE_RULES_H
)",
                       targetName,
                       targetUpper);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<RuleEntry> &rules)
{
    out << std::format(R"(// Auto-generated by EzDSL CppLegalizerRuleGenerator. DO NOT EDIT.

#include "{0}"
#include "Builder/MirBuilderContext.h"
#include "Instruction/MirInstruction.h"
#include "Instruction/MirInstructionBuilder.h"
#include "Operand/MirOperandBuilder.h"

namespace {1}
{{

bool {1}LegalizeRules::tryExpand(MirBuilderContext *ctx, MirInstruction *inst)
{{
    if (!ctx || !inst) return false;

)",
                       headerFileName,
                       targetName);

    // Optimized Decision Tree for Rule Dispatch
    for (const auto &rule : rules)
    {
        if (!rule.m_matchOpcode.empty())
        {
            out << std::format("    if (inst->getMnemonic() == \"{}\")\n    {{\n", rule.m_matchOpcode);
            out << std::format("        if (Expand_{}(ctx, inst)) return true;\n", rule.m_name);
            out << "    }\n";
        }
        else
        {
            out << std::format("    if (Expand_{}(ctx, inst)) return true;\n", rule.m_name);
        }
    }

    out << "    return false;\n}\n\n";

    for (const auto &rule : rules)
    {
        out << std::format(R"(bool {0}LegalizeRules::Expand_{1}(MirBuilderContext *ctx, MirInstruction *inst)
{{
    // Synthesized expansion logic for rule: {1} (match opcode: {2})
    (void)ctx;
    (void)inst;
    return false;
}}

)",
                           targetName,
                           rule.m_name,
                           rule.m_matchOpcode);
    }

    out << std::format("}} // namespace {}\n", targetName);
}

} // namespace

bool GenerateTargetLegalizerRules(DiagnosticCollector *collector,
                                  SymbolTable *table,
                                  std::filesystem::path outPath,
                                  std::string_view targetName,
                                  LegalizerRuleGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetLegalizerRules";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetLegalizerRules with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target legalize rules in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest Rewrite Rules from SymbolTable
    std::vector<RuleEntry> rules;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym) continue;

        const auto *ruleData = sym->getIf<Sema::Symbols::LegalizeRewriteRuleSymbol>();
        if (ruleData)
        {
            RuleEntry entry;
            entry.m_name = std::string(ruleData->m_ruleName);
            entry.m_patternCount = ruleData->m_matchPatterns.size();
            entry.m_expansionCount = ruleData->m_expansionSequence.size();
            if (!ruleData->m_matchPatterns.empty())
            {
                entry.m_matchOpcode = std::string(ruleData->m_matchPatterns[0].m_opcode);
            }
            rules.push_back(std::move(entry));
        }
    }

    // 3. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}LegalizeRules", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
    }

    std::string headerFileName = headerPath.filename().string();

    if (mode & LegalizerRuleGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName, rules);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & LegalizerRuleGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, rules);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized {} rewrite rules into {}",
                     rules.size(),
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
