#include "CodeGenerators/CppLegalizerGenerator.h"
#include "Ast/LegalizeActionDefLangAst.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace CodeGenerators
{

namespace
{

struct ClauseEntry
{
    DSL::Ast::LegalizeActionDef::LegalizeActionKind m_kind;
    std::vector<std::string> m_typeNames;
    std::vector<uint32_t> m_slotIndices;
    std::string m_targetType;
    std::string m_libcallSymbol;
};

struct ActionEntry
{
    std::string m_opcode;
    std::vector<ClauseEntry> m_clauses;
};

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

const char *GetActionKindName(DSL::Ast::LegalizeActionDef::LegalizeActionKind kind)
{
    switch (kind)
    {
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::Legal: return "LegalizeAction::Legal";
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::WidenScalar: return "LegalizeAction::WidenScalar";
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::NarrowScalar: return "LegalizeAction::NarrowScalar";
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::Libcall: return "LegalizeAction::Libcall";
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::Custom: return "LegalizeAction::Custom";
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::Bitcast: return "LegalizeAction::Bitcast";
        case DSL::Ast::LegalizeActionDef::LegalizeActionKind::Unsupported: return "LegalizeAction::Unsupported";
        default: return "LegalizeAction::Unsupported";
    }
}

void EmitHeader(std::ostream &out, std::string_view targetName)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_LEGALIZER_ACTION_TABLE_H
#define EZDSL_{0}_LEGALIZER_ACTION_TABLE_H

// Auto-generated by EzDSL CppLegalizerGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include "Legalizer/MirLegalizer.h"
#include <cstdint>
#include <string_view>

class MirBuilderContext;
class MirBlock;
class MirInstruction;
class TargetDesc;

namespace {1}
{{

/**
 * Legalization action kind for generic IR instructions.
 */
enum class LegalizeAction : uint8_t
{{
    Legal,
    WidenScalar,
    NarrowScalar,
    Libcall,
    Custom,
    Bitcast,
    Unsupported
}};

/**
 * Constant-time 2D/3D decision table query for {1} legalization actions.
 */
LegalizeAction GetTargetLegalizeAction(std::string_view genericOpcode, size_t slotIndex, std::string_view typeName);

/**
 * Returns true if the generic operation on the specified operand slot and type is natively legal.
 */
bool IsLegalTargetOperation(std::string_view genericOpcode, size_t slotIndex, std::string_view typeName);

/**
 * Concrete target machine legalizer for {1}.
 */
class {1}Legalizer : public MirLegalizer
{{
  public:
    {1}Legalizer(MirBuilderContext *ctx, TargetDesc *targetDesc);
    ~{1}Legalizer() override = default;

    LegalizationResult legalizeInstruction(IntrusiveLinkedList<MirInstruction>::iterator it, MirBlock *block) override;
}};

}} // namespace {1}

#endif // EZDSL_{0}_LEGALIZER_ACTION_TABLE_H
)",
                       targetUpper,
                       targetName);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<ActionEntry> &actions)
{
    out << std::format(R"(// Auto-generated by EzDSL CppLegalizerGenerator. DO NOT EDIT.

#include "{0}"
#include "Block/MirBlock.h"
#include "Builder/MirBuilderContext.h"
#include "Descriptors/TargetDesc.h"
#include "Function/MirFunction.h"
#include "Instruction/MirInstruction.h"
#include "Instruction/MirInstructionMetadata.h"
#include "Legalizer/Actions/LegalizeCallAction.h"
#include "Legalizer/Actions/LegalizeReturnAction.h"
#include "Legalizer/MirExpansionRuleRegistry.h"
#include "Operand/MirOperand.h"
#include "Type/MirType.h"

namespace {1}
{{

LegalizeAction GetTargetLegalizeAction(std::string_view genericOpcode, size_t slotIndex, std::string_view typeName)
{{
)",
                       headerFileName,
                       targetName);

    // Group actions into optimized decision tree
    for (const auto &action : actions)
    {
        out << std::format("    if (genericOpcode == \"{}\")\n    {{\n", action.m_opcode);
        for (const auto &clause : action.m_clauses)
        {
            const char *actionName = GetActionKindName(clause.m_kind);
            for (size_t i = 0; i < clause.m_typeNames.size(); ++i)
            {
                uint32_t slot = (i < clause.m_slotIndices.size()) ? clause.m_slotIndices[i] : 0;
                out << std::format("        if (slotIndex == {} && typeName == \"{}\") return {};\n",
                                   slot,
                                   clause.m_typeNames[i],
                                   actionName);
            }
        }
        out << "    }\n";
    }

    out << std::format(R"(    return LegalizeAction::Unsupported;
}}

bool IsLegalTargetOperation(std::string_view genericOpcode, size_t slotIndex, std::string_view typeName)
{{
    return GetTargetLegalizeAction(genericOpcode, slotIndex, typeName) == LegalizeAction::Legal;
}}

{0}Legalizer::{0}Legalizer(MirBuilderContext *ctx, TargetDesc *targetDesc) :
    MirLegalizer(ctx, targetDesc)
{{
}}

LegalizationResult {0}Legalizer::legalizeInstruction(IntrusiveLinkedList<MirInstruction>::iterator it, MirBlock *block)
{{
    if (!m_ctx) return LegalizationResult::Failed;

    MirInstruction *inst = *it;
    if (!inst) return LegalizationResult::NotModified;

    // 1. High-level call and return legalization
    LegalizeCtx ctx(m_ctx, m_targetDesc, it);
    if (inst->getFlags() & MirInstructionFlags::IsCall)
    {{
        return LegalizeActions::LegalizeCall(ctx);
    }}
    if (inst->getFlags() & MirInstructionFlags::IsReturn)
    {{
        return LegalizeActions::LegalizeReturn(ctx);
    }}

    // 2. Query target legality matrix for generic arithmetic & memory opcodes
    if (inst->getTargetDesc() == nullptr)
    {{
        std::string_view opName = inst->getMnemonic();
        size_t numOps = inst->getOperands().size();
        for (size_t slot = 0; slot < numOps; ++slot)
        {{
            MirOperand *op = inst->getOperand(slot);
            if (op && op->getMirType())
            {{
                std::string_view typeName = op->getMirType()->getName();
                LegalizeAction act = GetTargetLegalizeAction(opName, slot, typeName);
                if (act == LegalizeAction::Legal)
                {{
                    continue;
                }}
                if (act == LegalizeAction::Custom && m_targetDesc)
                {{
                    auto *expRules = m_targetDesc->getExpansionRegistry();
                    if (expRules && expRules->tryExpand(m_ctx, inst))
                    {{
                        return LegalizationResult::Legalized;
                    }}
                }}
            }}
        }}
    }}

    return MirLegalizer::legalizeInstruction(it, block);
}}

}} // namespace {0}
)",
                       targetName);
}

} // namespace

bool GenerateTargetLegalizerTable(DiagnosticCollector *collector,
                                  SymbolTable *table,
                                  std::filesystem::path outPath,
                                  std::string_view targetName,
                                  LegalizerGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetLegalizerTable";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetLegalizerTable with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target legalizer action table in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest Legalize Actions from SymbolTable
    std::vector<ActionEntry> actions;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym) continue;

        if (sym->getType() == SymbolType::LegalizeAction)
        {
            const auto *data = sym->getIf<Sema::Symbols::LegalizeActionSymbol>();
            if (data)
            {
                ActionEntry action;
                action.m_opcode = std::string(data->m_genericOpcode);

                for (const auto &clause : data->m_clauses)
                {
                    ClauseEntry cEntry;
                    cEntry.m_kind = clause.m_kind;
                    if (clause.m_libcallSymbol.has_value())
                    {
                        cEntry.m_libcallSymbol = std::string(*clause.m_libcallSymbol);
                    }

                    for (const auto &tCons : clause.m_types)
                    {
                        const Symbol *typeSym = table->getSymById(tCons.m_typeId);
                        if (typeSym)
                        {
                            cEntry.m_typeNames.push_back(std::string(typeSym->getName()));
                            cEntry.m_slotIndices.push_back(tCons.m_operandIndex.value_or(0));
                        }
                    }
                    action.m_clauses.push_back(std::move(cEntry));
                }

                actions.push_back(std::move(action));
            }
        }
    }

    // 3. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}LegalizerActionTable", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
    }

    std::string headerFileName = headerPath.filename().string();

    if (mode & LegalizerGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & LegalizerGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, actions);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized {} legalize action entries into {}",
                     actions.size(),
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
