#include "Ast/TypeDefLangAst.h"
#include "CodeGenerators/CppMirTypeTableGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

namespace CodeGenerators
{

namespace
{
struct GeneratedTypeEntry
{
    std::string m_name;
    uint32_t m_bitWidth{ 0 };
    DSL::Ast::TypeDef::TypeKind m_kind{ DSL::Ast::TypeDef::TypeKind::Integer };
    std::string m_fieldName;
    std::string m_getterName;
};

std::string KindToEnumString(DSL::Ast::TypeDef::TypeKind kind)
{
    switch (kind)
    {
        case DSL::Ast::TypeDef::TypeKind::Void:
            return "MirTypeKind::Void";
        case DSL::Ast::TypeDef::TypeKind::Integer:
            return "MirTypeKind::Integer";
        case DSL::Ast::TypeDef::TypeKind::FloatingPoint:
            return "MirTypeKind::FloatingPoint";
        case DSL::Ast::TypeDef::TypeKind::BindingToken:
            return "MirTypeKind::BindingToken";
        case DSL::Ast::TypeDef::TypeKind::Pointer:
            return "MirTypeKind::Pointer";
    }
    return "MirTypeKind::Integer";
}

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                // Unmodified content: preserve mtime to prevent unnecessary rebuild cascades
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

void EmitHeader(std::ostream &out, const std::vector<GeneratedTypeEntry> &types)
{
    out << R"(#ifndef EZMIR_MIR_TYPE_TABLE_H
#define EZMIR_MIR_TYPE_TABLE_H

// Auto-generated by EzDSL CppMirTypeTableGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include "Type/MirType.h"

/**
 * Class used to store the least minimum required types so everything else works.
 *
 * IMPORTANT: When created, types are aligned using the given target type layout (primitives).
 */
class MirTypeTable
{
  public:
    /**
     * Creates the type table with the given target type layout and arena allocator.
     */
    MirTypeTable(std::pmr::memory_resource *globalArena);

    // Disable copies to safeguard our arena resource mappings
    MirTypeTable(const MirTypeTable &) = delete;
    MirTypeTable &operator=(const MirTypeTable &) = delete;

    /**
     * Returns the target type layout used by this type table.
     */
    class IMirTargetTypeLayout *getTargetTypeLayout() const;

    /**
     * Creates a unique base or compound type. If there was an error while creating the type nullptr is returned.
     */
    MirType *create(MirTypeKind kind,
                    size_t totalSizeInBits,
                    std::pmr::vector<MirType *> subTypes,
                    const std::string_view &name);

    /**
     * Creates a function type with the given parameters. This function will CREATE only if it wasn't added before, if
     * it was the existing type is returned.
     */
    MirType *getFuncType(MirType *returnType,
                         const std::pmr::list<class MirRegister *> &parameters,
                         const std::string_view &funcName);

    /**
     * Interns pointer types. Guarantees that getPtr(T) always returns the exact same type instance pointer.
     */
    MirType *getPtr(MirType *srcType);

    /**
     * Interns array types structurally based on size and base element composition.
     */
    MirType *getArray(MirType *elementType, size_t elementCount);

    /**
     * Returns the first floating-point type that can hold the given bit size.
     */
    MirType *getFloatingTypeBySize(size_t sizeInBits) const;

    /**
     * Returns the first integer type that can hold the given bit size.
     */
    MirType *getIntegerTypeBySize(size_t sizeInBits) const;

    /**
     * Searches the table for the given ID and returns its type, if any. Returns nullptr if type was not created.
     */
    MirType *getMirTypeById(size_t id) const;

    // --- Built-in & Generated Type Accessors ---
)";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    MirType *{}();\n", type.m_getterName);
    }

    out << R"(
    /**
     * Initializes the type table with the basic primitive types needed as well as the type layout class.
     */
    void initialize(class IMirTargetTypeLayout *typeLayout);

  private:
    class IMirTargetTypeLayout *m_typeLayout{ nullptr };
    size_t m_currentId{ 0 };

    // Built-in & Generated Primitives
)";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    MirType *{}{{ nullptr }};\n", type.m_fieldName);
    }

    out << R"(
    std::pmr::memory_resource *m_arena;

    // High performance tracking hashes using PMR mapping blocks
    std::pmr::unordered_map<std::pmr::string, MirType *> m_typeNames;
    std::pmr::unordered_map<size_t, MirType *> m_idToType;

    // Interning caches: maps base type to its unique pointer type representation
    std::pmr::unordered_map<MirType *, MirType *> m_pointerCache;
};

#endif // EZMIR_MIR_TYPE_TABLE_H
)";
}

void EmitSource(std::ostream &out, const std::vector<GeneratedTypeEntry> &types)
{
    out << R"code(// Auto-generated by EzDSL CppMirTypeTableGenerator. DO NOT EDIT.

#include "Type/IMirTargetTypeLayout.h"
#include "Type/MirTypeTable.h"
#include "Operand/MirOperands.h"

MirTypeTable::MirTypeTable(std::pmr::memory_resource *globalArena) :
    m_typeLayout(nullptr), m_arena(globalArena), m_typeNames(globalArena), m_idToType(globalArena),
    m_pointerCache(globalArena)
{
}

IMirTargetTypeLayout *MirTypeTable::getTargetTypeLayout() const { return m_typeLayout; }

MirType *MirTypeTable::create(MirTypeKind kind,
                              size_t totalSizeInBits,
                              std::pmr::vector<MirType *> subTypes,
                              const std::string_view &name)
{
    if (name.empty())
    {
        return nullptr;
    }

    std::pmr::string lookupName(name, m_arena);
    auto it = m_typeNames.find(lookupName);
    if (it != m_typeNames.end())
    {
        return it->second;
    }

    size_t assignedId = ++m_currentId;

    size_t alignmentInBytes = 1;
    if (kind == MirTypeKind::Integer || kind == MirTypeKind::FloatingPoint || kind == MirTypeKind::Void)
    {
        MirType tempPrimitive(kind, this, assignedId, 1, totalSizeInBits, lookupName, {});
        alignmentInBytes = m_typeLayout->getTypeAlignmentInBytes(&tempPrimitive);
    }
    else if (kind == MirTypeKind::Pointer || kind == MirTypeKind::Function)
    {
        alignmentInBytes = m_typeLayout->getPointerSizeInBytes();
    }

    std::pmr::polymorphic_allocator<MirType> alloc(m_arena);
    MirType *uniqueType = alloc.new_object<MirType>(kind,
                                                    this,
                                                    assignedId,
                                                    alignmentInBytes,
                                                    totalSizeInBits,
                                                    lookupName,
                                                    std::move(subTypes));

    m_typeNames[lookupName] = uniqueType;
    m_idToType[assignedId] = uniqueType;

    return uniqueType;
}

MirType *MirTypeTable::getFuncType(MirType *returnType,
                                   const std::pmr::list<MirRegister *> &parameters,
                                   const std::string_view &funcName)
{
    if (!returnType)
    {
        return nullptr;
    }

    auto structuralSignature = returnType->getName();
    structuralSignature += "(";

    std::pmr::vector<MirType *> subTypes(m_arena);
    subTypes.reserve(parameters.size() + 1);
    subTypes.push_back(returnType);

    for (auto &param : parameters)
    {
        if (!param)
            continue;
        MirType *paramType = param->getMirType();
        subTypes.push_back(paramType);

        if (subTypes.size() > 2)
        {
            structuralSignature += ",";
        }
        structuralSignature += paramType->getName();
    }
    structuralSignature += ")";

    std::pmr::string lookupKey(structuralSignature, m_arena);
    auto it = m_typeNames.find(lookupKey);
    if (it != m_typeNames.end())
    {
        return it->second;
    }

    size_t pointerSizeInBits = m_typeLayout->getPointerSizeInBytes() * 8;
    return create(MirTypeKind::Function, pointerSizeInBits, std::move(subTypes), lookupKey);
}

MirType *MirTypeTable::getPtr(MirType *srcType)
{
    if (!srcType)
        return nullptr;

    auto it = m_pointerCache.find(srcType);
    if (it != m_pointerCache.end())
    {
        return it->second;
    }

    size_t pointerSizeInBytes = m_typeLayout->getPointerSizeInBytes();
    std::pmr::vector<MirType *> childTarget({ srcType }, m_arena);
    std::string formattedName = std::format("{}*", srcType->getName());

    MirType *newPointerType =
            create(MirTypeKind::Pointer, pointerSizeInBytes * 8, std::move(childTarget), formattedName);

    m_pointerCache[srcType] = newPointerType;
    return newPointerType;
}

MirType *MirTypeTable::getArray(MirType *elementType, size_t elementCount)
{
    if (!elementType)
        return nullptr;

    std::string arraySignature = std::format("{}[{}]", elementType->getName(), elementCount);
    std::pmr::string lookupName(arraySignature, m_arena);

    auto it = m_typeNames.find(lookupName);
    if (it != m_typeNames.end())
    {
        return it->second;
    }

    size_t totalSizeInBytes = m_typeLayout->getTypeSizeInBytes(elementType) * elementCount;
    size_t alignmentInBytes = m_typeLayout->getTypeAlignmentInBytes(elementType);
    std::pmr::vector<MirType *> childType({ elementType }, m_arena);

    std::pmr::polymorphic_allocator<MirType> alloc(m_arena);
    size_t assignedId = ++m_currentId;
    MirType *newArrayType = alloc.new_object<MirType>(MirTypeKind::Array,
                                                      this,
                                                      assignedId,
                                                      alignmentInBytes,
                                                      totalSizeInBytes * 8,
                                                      lookupName,
                                                      std::move(childType));

    m_typeNames[lookupName] = newArrayType;
    m_idToType[assignedId] = newArrayType;

    return newArrayType;
}

MirType *MirTypeTable::getFloatingTypeBySize(size_t sizeInBits) const
{
    MirType *result = nullptr;
    for (auto &[id, type] : m_idToType)
    {
        if (type->getKind() != MirTypeKind::FloatingPoint)
            continue;

        size_t typeSize = type->getTotalSizeInBits();
        if (typeSize >= sizeInBits)
        {
            if (!result || typeSize < result->getTotalSizeInBits())
            {
                result = type;
            }
        }
    }
    return result;
}

MirType *MirTypeTable::getIntegerTypeBySize(size_t sizeInBits) const
{
    MirType *result = nullptr;
    for (auto &[id, type] : m_idToType)
    {
        if (type->getKind() != MirTypeKind::Integer)
            continue;

        size_t typeSize = type->getTotalSizeInBits();
        if (typeSize >= sizeInBits)
        {
            if (!result || typeSize < result->getTotalSizeInBits())
            {
                result = type;
            }
        }
    }
    return result;
}

MirType *MirTypeTable::getMirTypeById(size_t id) const
{
    auto it = m_idToType.find(id);
    return (it != m_idToType.end()) ? it->second : nullptr;
}
)code";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("MirType *MirTypeTable::{}() {{ return {}; }}\n", type.m_getterName, type.m_fieldName);
    }

    out << R"(
void MirTypeTable::initialize(IMirTargetTypeLayout *typeLayout)
{
    m_typeLayout = typeLayout;
)";

    for (const auto &type : types)
    {
        if (type.m_kind == DSL::Ast::TypeDef::TypeKind::Pointer)
            continue;

        out << std::format("    {} = create({}, {}, {{}}, \"{}\");\n",
                           type.m_fieldName,
                           KindToEnumString(type.m_kind),
                           type.m_bitWidth,
                           type.m_name);
    }

    out << "}\n";
}

} // namespace

bool GenerateMirTypeTable(DiagnosticCollector *collector,
                          SymbolTable *table,
                          std::filesystem::path outPath,
                          MirTypeTableGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::MirTypeTable";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate MirTypeTable with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating type table in {}", outPath.string());

    // 1. Collect all type declarations from the symbol table
    std::vector<GeneratedTypeEntry> collectedTypes;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym || sym->getType() != SymbolType::Type)
        {
            continue;
        }

        const auto *data = sym->getIf<Sema::Symbols::TypeSymbol>();
        if (!data)
        {
            continue;
        }

        std::string typeName(sym->getName());

        collectedTypes.push_back(GeneratedTypeEntry{ .m_name = typeName,
                                                     .m_bitWidth = data->m_bitWidth,
                                                     .m_kind = data->m_kind,
                                                     .m_fieldName = std::format("m_{}Type", typeName),
                                                     .m_getterName = typeName });
    }

    // 2. Resolve destination file paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / "MirTypeTable.h";
        sourcePath = outPath / "MirTypeTable.cpp";
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
            if (ec)
            {
                collector->error(genName,
                                 "Failed to create directory {}: {}",
                                 outPath.parent_path().string(),
                                 ec.message());
                return false;
            }
        }

        if (outPath.extension() == ".h" || outPath.extension() == ".hpp")
        {
            headerPath = outPath;
            sourcePath = outPath;
            sourcePath.replace_extension(".cpp");
        }
        else
        {
            sourcePath = outPath;
            headerPath = outPath;
            headerPath.replace_extension(".h");
        }
    }

    // 3. Write Header if requested using WriteFileIfChanged
    if (mode & MirTypeTableGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, collectedTypes);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    // 4. Write Source if requested using WriteFileIfChanged
    if (mode & MirTypeTableGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, collectedTypes);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName, "Successfully generated {} type definitions", collectedTypes.size());

    return true;
}

} // namespace CodeGenerators