#include "CodeGenerators/CppTargetTypeLayoutGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace CodeGenerators
{

namespace
{

struct TypeEntry
{
    std::string m_name;
    uint32_t m_bitSize{ 32 };
    uint32_t m_alignment{ 4 };
};

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

void EmitHeader(std::ostream &out, std::string_view targetName, size_t pointerSize)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_TYPE_LAYOUT_H
#define EZDSL_{0}_TYPE_LAYOUT_H

// Auto-generated by EzDSL CppTargetTypeLayoutGenerator. DO NOT EDIT.

#include "Type/IMirTargetTypeLayout.h"
#include <cstddef>
#include <memory_resource>

namespace {1}
{{

/**
 * Concrete target type layout implementation for {1}.
 */
class {1}TargetTypeLayout : public IMirTargetTypeLayout
{{
  public:
    explicit {1}TargetTypeLayout(size_t pointerSize = {2}) : m_pointerSize(pointerSize) {{}}

    ~{1}TargetTypeLayout() override = default;

    size_t getPointerSizeInBytes() const override;

    size_t getTypeAlignmentInBytes(const MirType *type) const override;

    size_t getTypeSizeInBytes(const MirType *type) const override;

  private:
    size_t m_pointerSize;
}};

}} // namespace {1}

#endif // EZDSL_{0}_TYPE_LAYOUT_H
)",
                       targetUpper,
                       targetName,
                       pointerSize);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<TypeEntry> &types,
                size_t pointerSize)
{
    out << std::format(R"(// Auto-generated by EzDSL CppTargetTypeLayoutGenerator. DO NOT EDIT.

#include "{0}"
#include "Type/MirType.h"

namespace {1}
{{

size_t {1}TargetTypeLayout::getPointerSizeInBytes() const
{{
    return m_pointerSize;
}}

size_t {1}TargetTypeLayout::getTypeAlignmentInBytes(const MirType *type) const
{{
    if (!type) return 1;
    // Default alignment lookup based on type bit size
    size_t size = getTypeSizeInBytes(type);
    if (size >= 8) return 8;
    if (size >= 4) return 4;
    if (size >= 2) return 2;
    return 1;
}}

size_t {1}TargetTypeLayout::getTypeSizeInBytes(const MirType *type) const
{{
    if (!type) return 0;
    // MirType primitive queries
    switch (type->getKind())
    {{
        case MirTypeKind::Integer:
            return (type->getBitSize() + 7) / 8;
        case MirTypeKind::Float:
            return (type->getBitSize() + 7) / 8;
        case MirTypeKind::Pointer:
            return m_pointerSize;
        default:
            return (type->getBitSize() + 7) / 8;
    }}
}}

}} // namespace {1}
)",
                       headerFileName,
                       targetName);
}

} // namespace

bool GenerateTargetTypeLayout(DiagnosticCollector *collector,
                              SymbolTable *table,
                              std::filesystem::path outPath,
                              std::string_view targetName,
                              TargetTypeLayoutGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetTypeLayout";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetTypeLayout with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target type layout in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest Types from SymbolTable
    std::vector<TypeEntry> types;
    size_t pointerSize = 8; // Default 64-bit

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym) continue;

        if (sym->getType() == SymbolType::Type)
        {
            const auto *data = sym->getIf<Sema::Symbols::TypeSymbol>();
            if (data)
            {
                types.push_back(TypeEntry{
                    .m_name = std::string(sym->getName()),
                    .m_bitSize = data->m_bitWidth,
                    .m_alignment = (data->m_bitWidth + 7) / 8
                });
            }
        }
    }

    // 3. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}TypeLayout", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
    }

    std::string headerFileName = headerPath.filename().string();

    if (mode & TargetTypeLayoutGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName, pointerSize);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & TargetTypeLayoutGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, types, pointerSize);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized target type layout into {}",
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
