#include "CodeGenerators/CppTargetInstGenerator.h"
#include "Ast/InstructionDefLangAst.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace CodeGenerators
{

namespace
{

struct InstEntry
{
    std::string m_name;
    SymbolId m_symId{ InvalidSymbolId };
    SymbolId m_formatId{ InvalidSymbolId };
    std::string m_formatName;
    std::string m_asmTemplate;
    uint32_t m_latency{ 1 };
    uint32_t m_flagsMask{ 0 };
    std::vector<std::string> m_argNames;
    std::vector<std::string> m_implicitArgNames;
    size_t m_numExplicitDefs{ 0 };
    size_t m_numExplicitUses{ 0 };
    size_t m_numImplicitDefs{ 0 };
    size_t m_numImplicitUses{ 0 };
};

struct FormatEntry
{
    std::string m_name;
    SymbolId m_symId{ InvalidSymbolId };
    uint32_t m_bitWidth{ 32 };
};

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

void EmitHeader(std::ostream &out,
                std::string_view targetName,
                const std::vector<InstEntry> &instructions)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_INSTRUCTION_DEFS_H
#define EZDSL_{0}_INSTRUCTION_DEFS_H

// Auto-generated by EzDSL CppTargetInstGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include <cstdint>
#include <iosfwd>
#include <string_view>
#include <vector>

namespace {1}
{{

/**
 * Enumeration of all target hardware instruction opcodes for {1}.
 */
enum class TargetOpCode : uint16_t
{{
    TARGET_OPCODE_START = 1000,
)",
                       targetUpper,
                       targetName);

    for (const auto &inst : instructions)
    {
        out << std::format("    {},\n", inst.m_name);
    }

    out << std::format(R"(    TARGET_OPCODE_COUNT
}};

/**
 * Target instruction descriptor holding latency, behavioral flags, and operand properties.
 */
struct MirTargetInstructionDesc
{{
    const char *m_name;
    TargetOpCode m_opCode;
    uint32_t m_latency;
    uint32_t m_flags;
    size_t m_numExplicitDefs;
    size_t m_numExplicitUses;
    size_t m_numImplicitDefs;
    size_t m_numImplicitUses;
    const char *m_asmTemplate;
}};

/**
 * Retrieves the descriptor for the specified target instruction opcode.
 */
const MirTargetInstructionDesc &GetTargetInstructionDesc(TargetOpCode op);

/**
 * Returns the diagnostic string name of the target instruction opcode.
 */
const char *GetTargetOpCodeName(TargetOpCode op);

/**
 * Looks up a target instruction opcode by its name. Returns TargetOpCode::TARGET_OPCODE_START if not found.
 */
TargetOpCode GetTargetOpCodeByName(std::string_view name);

/**
 * Disassembles and prints the target instruction to an output stream using its declared assembly template.
 */
void PrintTargetInstruction(std::ostream &os, TargetOpCode op, const std::vector<std::string> &operands);

}} // namespace {1}

#endif // EZDSL_{0}_INSTRUCTION_DEFS_H
)",
                       targetUpper,
                       targetName);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<InstEntry> &instructions)
{
    out << std::format(R"(// Auto-generated by EzDSL CppTargetInstGenerator. DO NOT EDIT.

#include "{0}"
#include <algorithm>
#include <iostream>
#include <string>

namespace {1}
{{

static constexpr MirTargetInstructionDesc s_TargetInstructionDescs[] = {{
)",
                       headerFileName,
                       targetName);

    for (const auto &inst : instructions)
    {
        out << std::format("    {{ \"{0}\", TargetOpCode::{0}, {1}, {2}, {3}, {4}, {5}, {6}, \"{7}\" }},\n",
                           inst.m_name,
                           inst.m_latency,
                           inst.m_flagsMask,
                           inst.m_numExplicitDefs,
                           inst.m_numExplicitUses,
                           inst.m_numImplicitDefs,
                           inst.m_numImplicitUses,
                           inst.m_asmTemplate);
    }

    out << R"(};

static constexpr size_t TargetOpCount = sizeof(s_TargetInstructionDescs) / sizeof(s_TargetInstructionDescs[0]);

static const MirTargetInstructionDesc s_UnknownDesc = {
    "UNKNOWN", TargetOpCode::TARGET_OPCODE_START, 0, 0, 0, 0, 0, 0, ""
};

const MirTargetInstructionDesc &GetTargetInstructionDesc(TargetOpCode op)
{
    size_t rawVal = static_cast<size_t>(op);
    size_t startVal = static_cast<size_t>(TargetOpCode::TARGET_OPCODE_START);
    if (rawVal > startVal && rawVal <= startVal + TargetOpCount)
    {
        return s_TargetInstructionDescs[rawVal - startVal - 1];
    }
    return s_UnknownDesc;
}

const char *GetTargetOpCodeName(TargetOpCode op)
{
    return GetTargetInstructionDesc(op).m_name;
}

TargetOpCode GetTargetOpCodeByName(std::string_view name)
{
    for (size_t i = 0; i < TargetOpCount; ++i)
    {
        if (s_TargetInstructionDescs[i].m_name == name)
        {
            return s_TargetInstructionDescs[i].m_opCode;
        }
    }
    return TargetOpCode::TARGET_OPCODE_START;
}

void PrintTargetInstruction(std::ostream &os, TargetOpCode op, const std::vector<std::string> &operands)
{
    const auto &desc = GetTargetInstructionDesc(op);
    std::string tmpl(desc.m_asmTemplate);
    if (tmpl.empty())
    {
        os << desc.m_name;
        for (size_t i = 0; i < operands.size(); ++i)
        {
            os << (i == 0 ? " " : ", ") << operands[i];
        }
        return;
    }

    for (size_t i = 0; i < operands.size(); ++i)
    {
        std::string placeholder = "${" + std::to_string(i) + "}";
        size_t pos = 0;
        while ((pos = tmpl.find(placeholder, pos)) != std::string::npos)
        {
            tmpl.replace(pos, placeholder.length(), operands[i]);
            pos += operands[i].length();
        }
    }
    os << tmpl;
}

} // namespace )" << targetName << "\n";
}

void EmitEncoder(std::ostream &out,
                 std::string_view targetName,
                 std::string_view headerFileName,
                 const std::vector<InstEntry> &instructions)
{
    out << std::format(R"(// Auto-generated by EzDSL CppTargetInstGenerator. DO NOT EDIT.

#include "{0}"
#include "CodeSection.h"
#include <cstdint>
#include <vector>

namespace {1}
{{

)",
                       headerFileName,
                       targetName);

    for (const auto &inst : instructions)
    {
        out << std::format(R"(void Encode_{0}(CodeSection *sec, const std::vector<uint64_t> &operands)
{{
    if (!sec) return;
    (void)operands;
    // Default placeholder encoding logic for {0}
    sec->emit32(0x00000000);
}}

)",
                           inst.m_name);
    }

    out << std::format(R"(bool EncodeTargetInstruction(CodeSection *sec, TargetOpCode op, const std::vector<uint64_t> &operands)
{{
    if (!sec) return false;

    switch (op)
    {{
)",
                       targetName);

    for (const auto &inst : instructions)
    {
        out << std::format(R"(        case TargetOpCode::{0}:
            Encode_{0}(sec, operands);
            return true;
)",
                           inst.m_name);
    }

    out << R"(        default:
            return false;
    }
}

} // namespace )" << targetName << "\n";
}

} // namespace

bool GenerateTargetInstructionDefs(DiagnosticCollector *collector,
                                   SymbolTable *table,
                                   std::filesystem::path outPath,
                                   std::string_view targetName,
                                   TargetInstGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetInstructionDefs";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetInstructionDefs with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target instruction definitions in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest Instructions & Formats
    std::vector<InstEntry> instructions;
    std::vector<FormatEntry> formats;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym) continue;

        if (sym->getType() == SymbolType::Instruction)
        {
            const auto *data = sym->getIf<Sema::Symbols::TargetInstructionSymbol>();
            if (data)
            {
                InstEntry entry;
                entry.m_name = std::string(sym->getName());
                entry.m_symId = sym->getId();
                entry.m_formatId = data->m_formatId;
                entry.m_asmTemplate = std::string(data->m_asmTemplate);
                entry.m_latency = data->m_latency;
                entry.m_flagsMask = data->m_flagsMask;

                for (const auto &arg : data->m_args)
                {
                    entry.m_argNames.push_back(std::string(arg.m_name));
                    if (arg.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgOut ||
                        arg.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgInOut)
                    {
                        entry.m_numExplicitDefs++;
                    }
                    if (arg.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgIn ||
                        arg.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgInOut)
                    {
                        entry.m_numExplicitUses++;
                    }
                }

                for (const auto &imp : data->m_implicitArgs)
                {
                    entry.m_implicitArgNames.push_back(std::string(imp.m_name));
                    if (imp.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgOut ||
                        imp.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgInOut)
                    {
                        entry.m_numImplicitDefs++;
                    }
                    if (imp.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgIn ||
                        imp.m_dir == DSL::Ast::InstDef::InstOperandDir::ArgInOut)
                    {
                        entry.m_numImplicitUses++;
                    }
                }

                instructions.push_back(std::move(entry));
            }
        }
        else if (sym->getType() == SymbolType::InstructionFormat)
        {
            const auto *data = sym->getIf<Sema::Symbols::InstructionFormatSymbol>();
            if (data)
            {
                formats.push_back(FormatEntry{
                    .m_name = std::string(sym->getName()),
                    .m_symId = sym->getId(),
                    .m_bitWidth = data->m_bitWidth
                });
            }
        }
    }

    // 3. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::filesystem::path encoderPath;

    std::string baseName = std::format("{}InstructionDefs", resolvedTargetName);
    std::string encoderBase = std::format("{}BinaryEncoder", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
        encoderPath = outPath / std::format("{}.cpp", encoderBase);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
        encoderPath = outPath.parent_path() / std::format("{}.cpp", encoderBase);
    }

    std::string headerFileName = headerPath.filename().string();

    // 4. Emit requested artifacts
    if (mode & TargetInstGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName, instructions);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & TargetInstGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, instructions);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    if (mode & TargetInstGenWorkingMode::Encoder)
    {
        std::ostringstream encoderStream;
        EmitEncoder(encoderStream, resolvedTargetName, headerFileName, instructions);
        WriteFileIfChanged(encoderPath, encoderStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized {} target instructions and {} formats into {}",
                     instructions.size(),
                     formats.size(),
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
