#include "CodeGenerators/CppTargetDescGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

namespace CodeGenerators
{

namespace
{

void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

void EmitHeader(std::ostream &out, std::string_view targetName)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_TARGET_DESC_H
#define EZDSL_{0}_TARGET_DESC_H

// Auto-generated by EzDSL CppTargetDescGenerator. DO NOT EDIT.

#include "Descriptors/TargetBinaryDesc.h"
#include "Descriptors/TargetDesc.h"
#include <memory>
#include <memory_resource>

class IMirTargetTypeLayout;
class MirExpansionRuleRegistry;
class MirFrameLowerer;
class MirInstructionSelector;
class MirLegalizer;
class MirRegisterAllocator;

namespace {1}
{{

/**
 * Linux OS Binary Descriptor for {1}.
 */
class {1}LinuxBinaryDesc : public TargetBinaryDesc
{{
  public:
    bool isLittleEndian() const override {{ return true; }}
    bool isPositionIndependent() const override {{ return true; }}
    TargetCodeModel getCodeModel() const override {{ return TargetCodeModel::Small; }}
    TargetObjectFormat getObjectFormat() const override {{ return TargetObjectFormat::ELF64; }}
    size_t getFunctionAlignment() const override {{ return 16; }}
    size_t getLoopAlignment() const override {{ return 16; }}
    std::pmr::vector<TargetSectionDesc> getSections(std::pmr::memory_resource *alloc) const override
    {{
        return std::pmr::vector<TargetSectionDesc>(alloc);
    }}
}};

/**
 * Windows OS Binary Descriptor for {1}.
 */
class {1}WindowsBinaryDesc : public TargetBinaryDesc
{{
  public:
    bool isLittleEndian() const override {{ return true; }}
    bool isPositionIndependent() const override {{ return false; }}
    TargetCodeModel getCodeModel() const override {{ return TargetCodeModel::Small; }}
    TargetObjectFormat getObjectFormat() const override {{ return TargetObjectFormat::COFF64; }}
    size_t getFunctionAlignment() const override {{ return 16; }}
    size_t getLoopAlignment() const override {{ return 16; }}
    std::pmr::vector<TargetSectionDesc> getSections(std::pmr::memory_resource *alloc) const override
    {{
        return std::pmr::vector<TargetSectionDesc>(alloc);
    }}
}};

/**
 * Master target architecture descriptor for {1}.
 */
class {1}TargetDesc : public TargetDesc
{{
  public:
    explicit {1}TargetDesc(std::pmr::memory_resource *alloc);
    ~{1}TargetDesc() override = default;

    const char *getName() const override;
    IMirTargetTypeLayout *getTypeLayout() override;
    MirExpansionRuleRegistry *getExpansionRegistry() override;
    MirFrameLowerer *getFrameLowerer() override;
    MirInstructionSelector *getInstructionSelector() override;
    MirLegalizer *getLegalizer() override;
    MirRegisterAllocator *getRegisterAllocator() override;
    MirType *getMemOperandDisplacementType() override;
    MirType *getNearestLegalType(MirType *type) override;
    MirRegisterRef getInstructionPtrReg() const override;
    size_t getStackSlotSize() const override;
    void initialize() override;
    std::pmr::vector<TargetBinaryDesc *> getAvailableBinaryDescriptors() override;
    std::pmr::vector<CallingConvDesc *> getAvailableCallingConventions() override;
    std::pmr::vector<MirRegisterBank *> getAvailableRegisterBanks() override;

  private:
    std::pmr::memory_resource *m_alloc;
    std::unique_ptr<IMirTargetTypeLayout> m_layout;
    std::unique_ptr<MirLegalizer> m_legalizer;
    std::unique_ptr<MirExpansionRuleRegistry> m_rules;
    std::unique_ptr<MirInstructionSelector> m_isel;
    std::pmr::vector<TargetBinaryDesc *> m_binDescs;
    std::pmr::vector<CallingConvDesc *> m_callingConvs;
    std::pmr::vector<MirRegisterBank *> m_regBanks;
}};

/**
 * Factory function creating a fully synthesized instance of {1}TargetDesc.
 */
std::unique_ptr<TargetDesc> Create{1}TargetDesc(std::pmr::memory_resource *alloc);

}} // namespace {1}

#endif // EZDSL_{0}_TARGET_DESC_H
)",
                       targetUpper,
                       targetName);
}

void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName)
{
    out << std::format(R"(// Auto-generated by EzDSL CppTargetDescGenerator. DO NOT EDIT.

#include "{0}"
#include "{1}CallingConventions.h"
#include "{1}ISelTable.h"
#include "{1}LegalizeRules.h"
#include "{1}LegalizerActionTable.h"
#include "{1}RegisterBanks.h"
#include "{1}TypeLayout.h"

namespace {1}
{{

{1}TargetDesc::{1}TargetDesc(std::pmr::memory_resource *alloc) :
    m_alloc(alloc),
    m_binDescs(alloc),
    m_callingConvs(alloc),
    m_regBanks(alloc)
{{
}}

const char *{1}TargetDesc::getName() const
{{
    return "{1}";
}}

IMirTargetTypeLayout *{1}TargetDesc::getTypeLayout()
{{
    return m_layout.get();
}}

MirExpansionRuleRegistry *{1}TargetDesc::getExpansionRegistry()
{{
    return m_rules.get();
}}

MirFrameLowerer *{1}TargetDesc::getFrameLowerer()
{{
    return nullptr;
}}

MirInstructionSelector *{1}TargetDesc::getInstructionSelector()
{{
    return m_isel.get();
}}

MirLegalizer *{1}TargetDesc::getLegalizer()
{{
    return m_legalizer.get();
}}

MirRegisterAllocator *{1}TargetDesc::getRegisterAllocator()
{{
    return nullptr;
}}

MirType *{1}TargetDesc::getMemOperandDisplacementType()
{{
    return nullptr;
}}

MirType *{1}TargetDesc::getNearestLegalType(MirType *type)
{{
    return type;
}}

MirRegisterRef {1}TargetDesc::getInstructionPtrReg() const
{{
    return MirRegisterRef{{}};
}}

size_t {1}TargetDesc::getStackSlotSize() const
{{
    return 8;
}}

void {1}TargetDesc::initialize()
{{
    m_layout = std::make_unique<{1}TargetTypeLayout>();
    m_regBanks = CreateRegisterBanks(m_alloc);
    m_callingConvs = CreateAllCallingConventions(m_alloc);
    m_legalizer = std::make_unique<{1}Legalizer>(nullptr, this);
    m_rules = std::make_unique<{1}LegalizeRules>();
    m_isel = std::make_unique<{1}InstructionSelector>();

    static {1}LinuxBinaryDesc s_linuxDesc;
    static {1}WindowsBinaryDesc s_winDesc;
    m_binDescs.push_back(&s_linuxDesc);
    m_binDescs.push_back(&s_winDesc);
}}

std::pmr::vector<TargetBinaryDesc *> {1}TargetDesc::getAvailableBinaryDescriptors()
{{
    return m_binDescs;
}}

std::pmr::vector<CallingConvDesc *> {1}TargetDesc::getAvailableCallingConventions()
{{
    return m_callingConvs;
}}

std::pmr::vector<MirRegisterBank *> {1}TargetDesc::getAvailableRegisterBanks()
{{
    return m_regBanks;
}}

std::unique_ptr<TargetDesc> Create{1}TargetDesc(std::pmr::memory_resource *alloc)
{{
    auto desc = std::make_unique<{1}TargetDesc>(alloc);
    desc->initialize();
    return desc;
}}

}} // namespace {1}
)",
                       headerFileName,
                       targetName);
}

} // namespace

bool GenerateTargetDescriptor(DiagnosticCollector *collector,
                              SymbolTable *table,
                              std::filesystem::path outPath,
                              std::string_view targetName,
                              TargetDescGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetDescriptor";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetDescriptor with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target descriptor in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }
    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }
    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Resolve Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}TargetDesc", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
        }
        headerPath = outPath;
        sourcePath = outPath;
        sourcePath.replace_extension(".cpp");
    }

    std::string headerFileName = headerPath.filename().string();

    if (mode & TargetDescGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    if (mode & TargetDescGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized target descriptor into {}",
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
