#include "CodeGenerators/CppTargetBankGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/Symbols.h"

#include <algorithm>
#include <cctype>
#include <deque>
#include <filesystem>
#include <format>
#include <fstream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace CodeGenerators
{

namespace
{

/**
 * Metadata representation for a physical or sub-register during code generation.
 */
struct RegEntry
{
    std::string m_name;
    SymbolId m_symId{ InvalidSymbolId };
    std::optional<SymbolId> m_parentId;
    std::string m_parentName;
    uint32_t m_bitSize{ 0 };
    uint32_t m_bitOffset{ 0 };
    SymbolId m_primaryClassId{ InvalidSymbolId };
    std::string m_className;
    std::string m_bankName;

    size_t m_enumIndex{ 0 };
    SymbolId m_rootId{ InvalidSymbolId };
    std::string m_rootName;
    uint32_t m_absOffset{ 0 };

    std::vector<size_t> m_directChildren;
    std::vector<size_t> m_subRegs;
    std::vector<size_t> m_superRegs;
};

/**
 * Metadata representation for a register class during code generation.
 */
struct ClassEntry
{
    std::string m_name;
    SymbolId m_symId{ InvalidSymbolId };
    SymbolId m_bankId{ InvalidSymbolId };
    std::string m_bankName;
    std::vector<std::string> m_regNames;
    std::vector<size_t> m_regEnumIndices;
};

/**
 * Metadata representation for a hardware register bank during code generation.
 */
struct BankEntry
{
    std::string m_name;
    SymbolId m_symId{ InvalidSymbolId };
    std::vector<std::string> m_classNames;
};

/**
 * Writes newContent to filePath only if the file does not exist or its existing content differs.
 * Preserves file modification timestamps for unchanged content to prevent rebuild storms.
 */
void WriteFileIfChanged(const std::filesystem::path &filePath, const std::string &newContent)
{
    if (std::filesystem::exists(filePath))
    {
        std::ifstream currentFile(filePath, std::ios::in | std::ios::binary);
        if (currentFile.is_open())
        {
            std::ostringstream ss;
            ss << currentFile.rdbuf();
            if (ss.str() == newContent)
            {
                return;
            }
        }
    }

    std::ofstream outFile(filePath, std::ios::out | std::ios::trunc | std::ios::binary);
    if (outFile.is_open())
    {
        outFile << newContent;
    }
}

/**
 * Sanitizes an arbitrary identifier name to make it a valid C++ identifier / namespace.
 */
std::string SanitizeIdentifier(std::string_view name)
{
    if (name.empty())
    {
        return "Target";
    }

    std::string result;
    result.reserve(name.size());

    for (size_t i = 0; i < name.size(); ++i)
    {
        char c = name[i];
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            if (i == 0 && std::isdigit(static_cast<unsigned char>(c)))
            {
                result.push_back('_');
            }
            result.push_back(c);
        }
        else
        {
            result.push_back('_');
        }
    }

    return result;
}

/**
 * Converts a string to uppercase (for header inclusion guard generation).
 */
std::string ToUpperString(std::string_view str)
{
    std::string result;
    result.reserve(str.size());
    for (char c : str)
    {
        result.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
    }
    return result;
}

/**
 * Emits the C++ header file declaring register enumerations, aliasing helpers, and bank models.
 */
void EmitHeader(std::ostream &out,
                std::string_view targetName,
                const std::vector<BankEntry> &banks,
                const std::vector<ClassEntry> &classes,
                const std::vector<RegEntry> &regs)
{
    std::string targetUpper = ToUpperString(targetName);

    out << std::format(R"(#ifndef EZDSL_{0}_REGISTER_BANKS_H
#define EZDSL_{0}_REGISTER_BANKS_H

// Auto-generated by EzDSL CppTargetBankGenerator. DO NOT EDIT.

#include "EzCoreCommon.h"
#include "Operand/MirRegisterBank.h"
#include "Operand/MirRegisterClass.h"
#include "Operand/MirRegisterReference.h"

#include <array>
#include <cstdint>
#include <string_view>
#include <vector>

namespace {1}
{{

/**
 * Enumeration of all target hardware physical registers defined for {1}.
 */
enum class TargetReg : uint16_t
{{
    NoRegister = 0,
)",
                       targetUpper,
                       targetName);

    for (const auto &reg : regs)
    {
        out << std::format("    {},\n", reg.m_name);
    }

    out << std::format(R"(    TARGET_REG_COUNT
}};

/**
 * Returns the diagnostic string name of the target register.
 */
const char *GetRegisterName(TargetReg reg);

/**
 * Looks up a target register enum by its name. Returns TargetReg::NoRegister if not found.
 */
TargetReg GetRegisterByName(std::string_view name);

/**
 * Checks whether two physical target registers share underlying hardware storage (overlap/interfere).
 */
bool TargetRegistersOverlap(TargetReg regA, TargetReg regB);

/**
 * Returns all direct and indirect sub-registers (descendants) contained within the given register.
 */
const std::vector<TargetReg> &GetSubRegisters(TargetReg reg);

/**
 * Returns all direct and indirect super-registers (ancestors) that enclose the given register.
 */
const std::vector<TargetReg> &GetSuperRegisters(TargetReg reg);

/**
 * Container class managing initialized hardware register banks, register classes, and descriptors for {0}.
 */
class {0}RegisterBanks
{{
  public:
    /**
     * Constructs the target register bank model using the specified memory allocator.
     */
    explicit {0}RegisterBanks(std::pmr::memory_resource *alloc);

    // Disable copies to preserve allocator and pointer integrity
    {0}RegisterBanks(const {0}RegisterBanks &) = delete;
    {0}RegisterBanks &operator=(const {0}RegisterBanks &) = delete;

    /**
     * Initializes all register banks, register classes, descriptors, and sub-part hierarchies.
     */
    void initialize();

    /**
     * Retrieves a register bank by name, or nullptr if not found.
     */
    MirRegisterBank *getBank(std::string_view name) const;

    /**
     * Retrieves a register class by name, or nullptr if not found.
     */
    MirRegisterClass *getClass(std::string_view name) const;

    /**
     * Retrieves the physical register descriptor for a TargetReg enum value.
     */
    MirRegisterDescriptor *getRegisterDescriptor(TargetReg reg) const;

    /**
     * Retrieves the physical register descriptor for a register name.
     */
    MirRegisterDescriptor *getRegisterDescriptor(std::string_view name) const;

    /**
     * Creates a physical MirRegisterRef for the specified target register.
     */
    MirRegisterRef getRegisterRef(TargetReg reg) const;

    /**
     * Returns the list of all registered register banks.
     */
    const std::pmr::vector<MirRegisterBank *> &getBanks() const;

    /**
     * Returns the list of all registered register classes.
     */
    const std::pmr::vector<MirRegisterClass *> &getClasses() const;

    // --- Direct Bank Accessors ---
)",
                       targetName);

    for (const auto &bank : banks)
    {
        out << std::format("    MirRegisterBank *getBank_{}() const;\n", bank.m_name);
    }

    out << "\n    // --- Direct Class Accessors ---\n";
    for (const auto &cls : classes)
    {
        out << std::format("    MirRegisterClass *getClass_{}() const;\n", cls.m_name);
    }

    out << std::format(R"(
  private:
    std::pmr::memory_resource *m_alloc;
    std::pmr::vector<MirRegisterBank *> m_banks;
    std::pmr::vector<MirRegisterClass *> m_classes;
    std::pmr::unordered_map<std::pmr::string, MirRegisterBank *> m_bankMap;
    std::pmr::unordered_map<std::pmr::string, MirRegisterClass *> m_classMap;
    std::pmr::unordered_map<std::pmr::string, MirRegisterDescriptor *> m_regMap;
    std::array<MirRegisterDescriptor *, static_cast<size_t>(TargetReg::TARGET_REG_COUNT)> m_regDescs{{}};
}};

/**
 * Standalone factory function creating all register banks and classes for {0}.
 */
std::pmr::vector<MirRegisterBank *> CreateRegisterBanks(std::pmr::memory_resource *alloc);

}} // namespace {0}

#endif // EZDSL_{1}_REGISTER_BANKS_H
)",
                       targetName,
                       targetUpper);
}

/**
 * Emits the C++ source file implementing register lookups, overlap tables, and bank instantiation.
 */
void EmitSource(std::ostream &out,
                std::string_view targetName,
                std::string_view headerFileName,
                const std::vector<BankEntry> &banks,
                const std::vector<ClassEntry> &classes,
                const std::vector<RegEntry> &regs)
{
    size_t regCount = regs.size() + 1; // including NoRegister

    out << std::format(R"(// Auto-generated by EzDSL CppTargetBankGenerator. DO NOT EDIT.

#include "{0}"

#include <algorithm>
#include <cstring>

namespace {1}
{{

namespace
{{

struct RegNameEntry
{{
    TargetReg reg;
    const char *name;
}};

static constexpr RegNameEntry s_RegNames[] = {{
    {{ TargetReg::NoRegister, "NoRegister" }},
)",
                       headerFileName,
                       targetName);

    for (const auto &reg : regs)
    {
        out << std::format("    {{ TargetReg::{}, \"{}\" }},\n", reg.m_name, reg.m_name);
    }

    out << std::format(R"(}};

static constexpr size_t RegCount = static_cast<size_t>(TargetReg::TARGET_REG_COUNT);

static const bool s_OverlapTable[RegCount][RegCount] = {{
)");

    // Emit Overlap Matrix
    for (size_t i = 0; i < regCount; ++i)
    {
        out << "    /* " << (i == 0 ? "NoRegister" : regs[i - 1].m_name) << " */ { ";
        for (size_t j = 0; j < regCount; ++j)
        {
            bool overlap = false;
            if (i > 0 && j > 0)
            {
                const auto &regA = regs[i - 1];
                const auto &regB = regs[j - 1];
                if (regA.m_rootId == regB.m_rootId)
                {
                    uint32_t startA = regA.m_absOffset;
                    uint32_t endA = startA + regA.m_bitSize;
                    uint32_t startB = regB.m_absOffset;
                    uint32_t endB = startB + regB.m_bitSize;
                    overlap = (std::max(startA, startB) < std::min(endA, endB));
                }
            }
            out << (overlap ? "true" : "false") << (j + 1 < regCount ? ", " : " ");
        }
        out << "},\n";
    }

    out << "};\n\n";

    // Emit Sub-Registers table
    out << "static const std::vector<TargetReg> s_SubRegs[RegCount] = {\n";
    out << "    /* NoRegister */ {},\n";
    for (size_t i = 0; i < regs.size(); ++i)
    {
        const auto &reg = regs[i];
        out << std::format("    /* {} */ {{ ", reg.m_name);
        for (size_t k = 0; k < reg.m_subRegs.size(); ++k)
        {
            size_t childIdx = reg.m_subRegs[k];
            out << std::format("TargetReg::{}", regs[childIdx - 1].m_name);
            if (k + 1 < reg.m_subRegs.size())
            {
                out << ", ";
            }
        }
        out << " },\n";
    }
    out << "};\n\n";

    // Emit Super-Registers table
    out << "static const std::vector<TargetReg> s_SuperRegs[RegCount] = {\n";
    out << "    /* NoRegister */ {},\n";
    for (size_t i = 0; i < regs.size(); ++i)
    {
        const auto &reg = regs[i];
        out << std::format("    /* {} */ {{ ", reg.m_name);
        for (size_t k = 0; k < reg.m_superRegs.size(); ++k)
        {
            size_t parentIdx = reg.m_superRegs[k];
            out << std::format("TargetReg::{}", regs[parentIdx - 1].m_name);
            if (k + 1 < reg.m_superRegs.size())
            {
                out << ", ";
            }
        }
        out << " },\n";
    }
    out << "};\n\n";

    out << R"(} // namespace

const char *GetRegisterName(TargetReg reg)
{
    size_t idx = static_cast<size_t>(reg);
    if (idx < RegCount)
    {
        return s_RegNames[idx].name;
    }
    return "UnknownRegister";
}

TargetReg GetRegisterByName(std::string_view name)
{
    for (const auto &entry : s_RegNames)
    {
        if (entry.name == name)
        {
            return entry.reg;
        }
    }
    return TargetReg::NoRegister;
}

bool TargetRegistersOverlap(TargetReg regA, TargetReg regB)
{
    size_t idxA = static_cast<size_t>(regA);
    size_t idxB = static_cast<size_t>(regB);
    if (idxA >= RegCount || idxB >= RegCount)
    {
        return false;
    }
    return s_OverlapTable[idxA][idxB];
}

const std::vector<TargetReg> &GetSubRegisters(TargetReg reg)
{
    size_t idx = static_cast<size_t>(reg);
    if (idx < RegCount)
    {
        return s_SubRegs[idx];
    }
    static const std::vector<TargetReg> empty;
    return empty;
}

const std::vector<TargetReg> &GetSuperRegisters(TargetReg reg)
{
    size_t idx = static_cast<size_t>(reg);
    if (idx < RegCount)
    {
        return s_SuperRegs[idx];
    }
    static const std::vector<TargetReg> empty;
    return empty;
}
)";

    // Class implementation
    out << std::format(R"(
{0}RegisterBanks::{0}RegisterBanks(std::pmr::memory_resource *alloc) :
    m_alloc(alloc),
    m_banks(alloc),
    m_classes(alloc),
    m_bankMap(alloc),
    m_classMap(alloc),
    m_regMap(alloc)
{{
    m_regDescs.fill(nullptr);
}}

void {0}RegisterBanks::initialize()
{{
    std::pmr::polymorphic_allocator<std::byte> byteAlloc(m_alloc);

    // 1. Allocate Register Banks and Classes
)",
                       targetName);

    for (const auto &bank : banks)
    {
        out << std::format(R"(    auto *bank_{0} = byteAlloc.new_object<MirRegisterBank>("{0}", m_alloc);
    m_banks.push_back(bank_{0});
    m_bankMap[std::pmr::string("{0}", m_alloc)] = bank_{0};

)",
                           bank.m_name);

        for (const auto &clsName : bank.m_classNames)
        {
            out << std::format(R"(    auto *cls_{0} = byteAlloc.new_object<MirRegisterClass>("{0}", bank_{1}, m_alloc);
    bank_{1}->addClass("{0}", cls_{0});
    m_classes.push_back(cls_{0});
    m_classMap[std::pmr::string("{0}", m_alloc)] = cls_{0};

)",
                               clsName,
                               bank.m_name);
        }
    }

    out << "    // 2. Register descriptors in respective classes\n";
    for (const auto &cls : classes)
    {
        for (size_t regIdx : cls.m_regEnumIndices)
        {
            const auto &reg = regs[regIdx - 1];
            out << std::format("    cls_{}->addRegister(\"{}\", {}, {}, {{}});\n",
                               cls.m_name,
                               reg.m_name,
                               reg.m_bitSize,
                               reg.m_bitOffset);
        }
    }

    out << "\n    // 3. Populate fast descriptor lookup maps and arrays\n";
    for (const auto &cls : classes)
    {
        for (size_t regIdx : cls.m_regEnumIndices)
        {
            const auto &reg = regs[regIdx - 1];
            out << std::format("    auto *desc_{0} = cls_{1}->getReg(\"{0}\");\n"
                               "    if (desc_{0})\n"
                               "    {{\n"
                               "        m_regMap[std::pmr::string(\"{0}\", m_alloc)] = desc_{0};\n"
                               "        m_regDescs[static_cast<size_t>(TargetReg::{0})] = desc_{0};\n"
                               "    }}\n",
                               reg.m_name,
                               cls.m_name);
        }
    }

    out << "\n    // 4. Link sub-register hierarchies (direct children)\n";
    for (const auto &reg : regs)
    {
        if (!reg.m_directChildren.empty())
        {
            for (size_t childIdx : reg.m_directChildren)
            {
                const auto &childReg = regs[childIdx - 1];
                out << std::format("    if (desc_{0} && desc_{1}) desc_{0}->m_subParts.push_back(desc_{1});\n",
                                   reg.m_name,
                                   childReg.m_name);
            }
        }
    }

    out << std::format(R"(}}

MirRegisterBank *{0}RegisterBanks::getBank(std::string_view name) const
{{
    std::pmr::string lookupKey(name, m_alloc);
    auto it = m_bankMap.find(lookupKey);
    return it != m_bankMap.end() ? it->second : nullptr;
}}

MirRegisterClass *{0}RegisterBanks::getClass(std::string_view name) const
{{
    std::pmr::string lookupKey(name, m_alloc);
    auto it = m_classMap.find(lookupKey);
    return it != m_classMap.end() ? it->second : nullptr;
}}

MirRegisterDescriptor *{0}RegisterBanks::getRegisterDescriptor(TargetReg reg) const
{{
    size_t idx = static_cast<size_t>(reg);
    return idx < RegCount ? m_regDescs[idx] : nullptr;
}}

MirRegisterDescriptor *{0}RegisterBanks::getRegisterDescriptor(std::string_view name) const
{{
    std::pmr::string lookupKey(name, m_alloc);
    auto it = m_regMap.find(lookupKey);
    return it != m_regMap.end() ? it->second : nullptr;
}}

MirRegisterRef {0}RegisterBanks::getRegisterRef(TargetReg reg) const
{{
    MirRegisterDescriptor *desc = getRegisterDescriptor(reg);
    return desc ? MirRegisterRef::preg(desc) : MirRegisterRef{{}};
}}

const std::pmr::vector<MirRegisterBank *> &{0}RegisterBanks::getBanks() const
{{
    return m_banks;
}}

const std::pmr::vector<MirRegisterClass *> &{0}RegisterBanks::getClasses() const
{{
    return m_classes;
}}

)",
                       targetName);

    for (const auto &bank : banks)
    {
        out << std::format("MirRegisterBank *{}RegisterBanks::getBank_{}() const {{ return getBank(\"{}\"); }}\n",
                           targetName,
                           bank.m_name,
                           bank.m_name);
    }

    for (const auto &cls : classes)
    {
        out << std::format("MirRegisterClass *{}RegisterBanks::getClass_{}() const {{ return getClass(\"{}\"); }}\n",
                           targetName,
                           cls.m_name,
                           cls.m_name);
    }

    out << std::format(R"(
std::pmr::vector<MirRegisterBank *> CreateRegisterBanks(std::pmr::memory_resource *alloc)
{{
    std::pmr::polymorphic_allocator<{0}RegisterBanks> modelAlloc(alloc);
    auto *model = modelAlloc.new_object<{0}RegisterBanks>(alloc);
    model->initialize();
    return model->getBanks();
}}

}} // namespace {0}
)",
                       targetName);
}

} // namespace

bool GenerateTargetRegisterBanks(DiagnosticCollector *collector,
                                 SymbolTable *table,
                                 std::filesystem::path outPath,
                                 std::string_view targetName,
                                 TargetBankGenWorkingMode mode)
{
    constexpr auto genName = "CodeGenerators::TargetRegisterBanks";

    if (!collector)
    {
        return false;
    }

    if (!table)
    {
        collector->error(genName, "Cannot generate TargetRegisterBanks with a null SymbolTable.");
        return false;
    }

    collector->trace(genName, "Generating target register banks in {}", outPath.string());

    // 1. Resolve Target Name
    std::string resolvedTargetName(targetName);
    if (resolvedTargetName.empty())
    {
        for (const Symbol *sym : table->getSymbols())
        {
            if (sym && sym->getType() == SymbolType::Target)
            {
                resolvedTargetName = sym->getName();
                break;
            }
        }
    }

    if (resolvedTargetName.empty())
    {
        resolvedTargetName = "Target";
    }

    resolvedTargetName = SanitizeIdentifier(resolvedTargetName);

    // 2. Ingest Banks, Classes, and Registers from SymbolTable
    std::vector<BankEntry> banks;
    std::vector<ClassEntry> classes;
    std::vector<RegEntry> regs;

    std::unordered_map<SymbolId, size_t> bankSymIdToIndex;
    std::unordered_map<SymbolId, size_t> classSymIdToIndex;
    std::unordered_map<SymbolId, size_t> regSymIdToIndex;

    for (const Symbol *sym : table->getSymbols())
    {
        if (!sym)
        {
            continue;
        }

        if (sym->getType() == SymbolType::RegisterBank)
        {
            const auto *data = sym->getIf<Sema::Symbols::RegisterBankSymbol>();
            if (data)
            {
                bankSymIdToIndex[sym->getId()] = banks.size();
                banks.push_back(BankEntry{ .m_name = std::string(sym->getName()), .m_symId = sym->getId() });
            }
        }
        else if (sym->getType() == SymbolType::RegisterClass)
        {
            const auto *data = sym->getIf<Sema::Symbols::RegisterClassSymbol>();
            if (data)
            {
                classSymIdToIndex[sym->getId()] = classes.size();
                classes.push_back(ClassEntry{ .m_name = std::string(sym->getName()),
                                              .m_symId = sym->getId(),
                                              .m_bankId = data->m_bankId });
            }
        }
        else if (sym->getType() == SymbolType::Register)
        {
            const auto *data = sym->getIf<Sema::Symbols::RegisterSymbol>();
            if (data)
            {
                regSymIdToIndex[sym->getId()] = regs.size();
                regs.push_back(RegEntry{ .m_name = std::string(sym->getName()),
                                         .m_symId = sym->getId(),
                                         .m_parentId = data->m_parentId,
                                         .m_bitSize = data->m_bitSize,
                                         .m_bitOffset = data->m_bitOffset,
                                         .m_primaryClassId = data->m_primaryClassId });
            }
        }
    }

    // Link Bank -> Classes
    for (auto &cls : classes)
    {
        auto bIt = bankSymIdToIndex.find(cls.m_bankId);
        if (bIt != bankSymIdToIndex.end())
        {
            cls.m_bankName = banks[bIt->second].m_name;
            banks[bIt->second].m_classNames.push_back(cls.m_name);
        }
    }

    // Link Class -> Registers
    for (size_t i = 0; i < regs.size(); ++i)
    {
        auto &reg = regs[i];
        reg.m_enumIndex = i + 1; // 1-based index (0 is NoRegister)

        auto cIt = classSymIdToIndex.find(reg.m_primaryClassId);
        if (cIt != classSymIdToIndex.end())
        {
            reg.m_className = classes[cIt->second].m_name;
            reg.m_bankName = classes[cIt->second].m_bankName;
            classes[cIt->second].m_regNames.push_back(reg.m_name);
            classes[cIt->second].m_regEnumIndices.push_back(reg.m_enumIndex);
        }

        if (reg.m_parentId.has_value())
        {
            auto pIt = regSymIdToIndex.find(*reg.m_parentId);
            if (pIt != regSymIdToIndex.end())
            {
                reg.m_parentName = regs[pIt->second].m_name;
            }
        }
    }

    // 3. Compute Register Hierarchy, Roots, Offsets, and Ancestors
    for (auto &reg : regs)
    {
        SymbolId current = reg.m_symId;
        uint32_t totalOffset = 0;
        std::vector<size_t> ancestors;

        while (true)
        {
            auto it = regSymIdToIndex.find(current);
            if (it == regSymIdToIndex.end())
            {
                break;
            }

            const auto &currReg = regs[it->second];
            if (current != reg.m_symId)
            {
                ancestors.push_back(currReg.m_enumIndex);
            }

            if (!currReg.m_parentId.has_value())
            {
                reg.m_rootId = currReg.m_symId;
                reg.m_rootName = currReg.m_name;
                break;
            }

            totalOffset += currReg.m_bitOffset;
            current = *currReg.m_parentId;
        }

        reg.m_absOffset = totalOffset;
        reg.m_superRegs = ancestors;
    }

    // Compute Direct Children
    for (const auto &reg : regs)
    {
        if (reg.m_parentId.has_value())
        {
            auto pIt = regSymIdToIndex.find(*reg.m_parentId);
            if (pIt != regSymIdToIndex.end())
            {
                regs[pIt->second].m_directChildren.push_back(reg.m_enumIndex);
            }
        }
    }

    // Compute Sub-Registers (transitive descendants) via BFS
    for (auto &reg : regs)
    {
        std::queue<size_t> workList;
        for (size_t childIdx : reg.m_directChildren)
        {
            workList.push(childIdx);
        }

        while (!workList.empty())
        {
            size_t childIdx = workList.front();
            workList.pop();

            reg.m_subRegs.push_back(childIdx);
            for (size_t nextChild : regs[childIdx - 1].m_directChildren)
            {
                workList.push(nextChild);
            }
        }
    }

    // 4. Resolve Output File Paths
    std::filesystem::path headerPath;
    std::filesystem::path sourcePath;
    std::string baseName = std::format("{}RegisterBanks", resolvedTargetName);

    if (std::filesystem::is_directory(outPath) || !outPath.has_extension())
    {
        std::error_code ec;
        std::filesystem::create_directories(outPath, ec);
        if (ec)
        {
            collector->error(genName, "Failed to create directory {}: {}", outPath.string(), ec.message());
            return false;
        }
        headerPath = outPath / std::format("{}.h", baseName);
        sourcePath = outPath / std::format("{}.cpp", baseName);
    }
    else
    {
        if (outPath.has_parent_path())
        {
            std::error_code ec;
            std::filesystem::create_directories(outPath.parent_path(), ec);
            if (ec)
            {
                collector->error(genName,
                                 "Failed to create directory {}: {}",
                                 outPath.parent_path().string(),
                                 ec.message());
                return false;
            }
        }

        if (outPath.extension() == ".h" || outPath.extension() == ".hpp")
        {
            headerPath = outPath;
            sourcePath = outPath;
            sourcePath.replace_extension(".cpp");
        }
        else
        {
            sourcePath = outPath;
            headerPath = outPath;
            headerPath.replace_extension(".h");
        }
    }

    std::string headerFileName = headerPath.filename().string();

    // 5. Emit Header if requested
    if (mode & TargetBankGenWorkingMode::Header)
    {
        std::ostringstream headerStream;
        EmitHeader(headerStream, resolvedTargetName, banks, classes, regs);
        WriteFileIfChanged(headerPath, headerStream.str());
    }

    // 6. Emit Source if requested
    if (mode & TargetBankGenWorkingMode::Source)
    {
        std::ostringstream sourceStream;
        EmitSource(sourceStream, resolvedTargetName, headerFileName, banks, classes, regs);
        WriteFileIfChanged(sourcePath, sourceStream.str());
    }

    collector->trace(genName,
                     "Successfully synthesized {} registers across {} classes and {} banks into {}",
                     regs.size(),
                     classes.size(),
                     banks.size(),
                     headerPath.filename().string());

    return true;
}

} // namespace CodeGenerators
