#ifndef EZDSL_SYMBOL_H
#define EZDSL_SYMBOL_H

#include "EzDslCommon.h"
#include "Symbols/Symbols.h"

/**
 * Bitflags tracking definition state, reference count, synthetic generation, and error poisoning on symbols.
 */
enum class SymbolFlags : uint8_t
{
    None = 0,
    IsDefined = 1 << 0,
    IsReferenced = 1 << 1,
    IsSynthetic = 1 << 2, // Generated by compiler pass
    HasErrors = 1 << 3    // Poisoned symbol to avoid duplicate diagnostics
};

/**
 * Discriminator enum identifying the syntactic/semantic category of a Symbol.
 */
enum class SymbolType : uint8_t
{
    // .tdf Target entities
    Register,
    RegisterClass,
    RegisterBank,

    // .idf Instruction entities
    InstructionFormat,
    FormatField,
    Instruction,

    // .lad action symbol.
    LegalizeAction,

    // .lrd / .isf Patterns & SSA entities
    SsaVariable,
    LegalizeRule,
    AddrMode,
    ISelPattern,

    // .tyf Type File
    Type,

    // .irdf IR instruction entities.
    IrInstruction,

    // .ccdf Calling convention entities
    CallingConv,

    // Target entity
    Target
};

/**
 * Bitwise OR operator for combining SymbolFlags bitmasks.
 */
constexpr SymbolFlags operator|(SymbolFlags a, SymbolFlags b) noexcept
{
    return static_cast<SymbolFlags>(static_cast<uint8_t>(a) | static_cast<uint8_t>(b));
}

/**
 * Bitwise AND test operator checking if any common flags are set.
 */
constexpr bool operator&(SymbolFlags a, SymbolFlags b) noexcept
{
    return (static_cast<uint8_t>(a) & static_cast<uint8_t>(b)) != 0;
}

/**
 * Universal symbol table entry representing named definitions across all EzDsl sub-languages.
 * Holds typed semantic payload in a std::variant.
 */
class Symbol
{
  public:
    using SymbolData = std::variant<std::monostate,
                                    Sema::Symbols::TypeSymbol,
                                    Sema::Symbols::RegisterSymbol,
                                    Sema::Symbols::RegisterClassSymbol,
                                    Sema::Symbols::RegisterBankSymbol,
                                    Sema::Symbols::InstructionFormatSymbol,
                                    Sema::Symbols::TargetInstructionSymbol,
                                    Sema::Symbols::IrInstructionSymbol,
                                    Sema::Symbols::LegalizeActionSymbol,
                                    Sema::Symbols::LegalizeRewriteRuleSymbol,
                                    Sema::Symbols::AddrModeSymbol,
                                    Sema::Symbols::ISelPatternSymbol,
                                    Sema::Symbols::CallingConvSymbol,
                                    Sema::Symbols::TargetSymbol>;

    /**
     * Constructs a symbol with source location span, flags, defining scope ID, unique symbol ID, type, and name.
     */
    Symbol(class SourceReference *sourceRef,
           SymbolFlags flags,
           SymbolId definingScope,
           SymbolId id,
           SymbolType type,
           std::string_view name);

    /**
     * Checks if the symbol holds semantic data of type T in its variant payload.
     */
    template <typename T> bool hasData() const { return std::holds_alternative<T>(m_data); }

    /**
     * Checks if the specified symbol flag bit is set.
     */
    bool hasFlag(SymbolFlags flag) const;

    /**
     * Returns the SourceReference span representing the symbol's declaration location.
     */
    class SourceReference *getSourceRef() const;

    /**
     * Returns the symbol flags bitmask.
     */
    SymbolFlags getFlags() const;

    /**
     * Returns the unique ID of the lexical/semantic scope that contains this symbol.
     */
    SymbolId getDefiningScopeId() const;

    /**
     * Returns the unique numeric ID assigned to this symbol.
     */
    SymbolId getId() const;

    /**
     * Returns the symbol category type.
     */
    SymbolType getType() const;

    /**
     * Returns a mutable pointer to the payload if it matches type T, or nullptr otherwise.
     */
    template <typename T> T *getIf() { return std::get_if<T>(&m_data); }

    /**
     * Const overload returning a read-only pointer to the payload of type T, or nullptr if unmatched.
     */
    template <typename T> const T *getIf() const { return std::get_if<T>(&m_data); }

    /**
     * Sets or overwrites the symbol's semantic data payload.
     */
    void setData(SymbolData data);

    /**
     * Returns the textual identifier name of the symbol.
     */
    const std::string_view &getName() const;

  private:
    class SourceReference *m_sourceRef;
    SymbolData m_data;
    SymbolFlags m_flags;
    SymbolId m_definingScopeId; // Same datatype as ScopeId but we can't use here...
    SymbolId m_id;
    SymbolType m_type;
    std::string_view m_name;
};

#endif // EZDSL_SYMBOL_H