#ifndef EZDSL_SYMBOL_H
#define EZDSL_SYMBOL_H

#include "EzDslCommon.h"

using SymbolId = size_t;
inline constexpr SymbolId InvalidSymbolId = UINT64_MAX;

enum class SymbolFlags : uint8_t
{
    None = 0,
    IsDefined = 1 << 0,
    IsReferenced = 1 << 1,
    IsSynthetic = 1 << 2, // Generated by compiler pass
    HasErrors = 1 << 3    // Poisoned symbol to avoid duplicate diagnostics
};

enum class SymbolType : uint8_t
{
    // .tdf Target entities
    Register,
    RegisterClass,
    RegisterBank,

    // .idf Instruction entities
    InstructionFormat,
    FormatField,
    Instruction,

    // .lad / .god Opcode entities
    GenericOpcode,
    TargetOpcode,

    // .lrd / .isf Patterns & SSA entities
    SsaVariable,
    AddrMode,
    ISelPattern,
};

constexpr SymbolFlags operator|(SymbolFlags a, SymbolFlags b) noexcept
{
    return static_cast<SymbolFlags>(static_cast<uint8_t>(a) | static_cast<uint8_t>(b));
}
constexpr bool operator&(SymbolFlags a, SymbolFlags b) noexcept
{
    return (static_cast<uint8_t>(a) & static_cast<uint8_t>(b)) != 0;
}

class Symbol
{
  public:
    /**
     * Creates the symbol with the given source reference, flags, definition scope, id, type and name. Data is NOT set.
     */
    Symbol(class SourceReference *sourceRef,
           SymbolFlags flags,
           SymbolId definingScope,
           SymbolId id,
           SymbolType type,
           std::string_view name);

    /**
     * Returns the source reference linked to this symbol.
     */
    class SourceReference *getSourceRef() const;

    /**
     * Returns the flags of the symbol.
     */
    SymbolFlags getFlags() const;

    /**
     * Returns the ID of the scope that defined this symbol.
     */
    SymbolId getDefiningScopeId() const;

    /**
     * Returns the ID of the symbol.
     */
    SymbolId getId() const;

    /**
     * Returns the type of the symbol.
     */
    SymbolType getType() const;

    /**
     * Returns the name of the symbol.
     */
    const std::string_view &getName() const;

  private:
    class SourceReference *m_sourceRef;
    SymbolFlags m_flags;
    SymbolId m_definingScopeId; // Same datatype as ScopeId but we can't use here...
    SymbolId m_id;
    SymbolType m_type;
    std::string_view m_name;
};

#endif // EZDSL_SYMBOL_H