#include "EzDslCodeGeneratorsTestSuite.h"
#include "Ast/RegisterDefLangAst.h"
#include "CodeGenerators/CppRegisterInfoGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Parser/ParseContext.h"
#include "Parser/RegisterDefLang.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "SemaPasses/RegisterPass.h"

#include <chrono>
#include <filesystem>

using namespace CodeGenerators;

/**
 * Test fixture for the header-only register info generator.
 */
class CppRegisterInfoGeneratorTest : public EzDslCodeGeneratorsTestSuiteAsGtest
{
  protected:
    bool parseAndRunPass(const std::string &source)
    {
        ParseContext ctx = createParseContextFromBuff(std::format("gen_reg_{}.reg", m_sourceId++), source);
        m_ast = ctx.parse<DSL::Parser::RegisterDef::RegisterDefFile, DSL::Ast::RegisterDef::RegisterFile>();
        if (!m_ast.has_value())
        {
            return false;
        }

        RegisterPass pass;
        return pass.run(getDiagCollector(), getSymbolTable(), &m_ast.value());
    }

    static constexpr const char *s_validRegisterFile = R"(
target X86_64;

register_bank GPR {
    classes { GPR8: 8, GPR16: 16, GPR32: 32, GPR64: 64 }
    sub_register { GPR16 <: GPR8, GPR32 <: GPR16, GPR64 <: GPR32 }
    registers {
        rax enc 0  names { rax: GPR64, eax: GPR32, ax: GPR16, al: GPR8 }
        rcx enc 1  names { rcx: GPR64, ecx: GPR32, cx: GPR16, cl: GPR8 }
    }
}

register_bank FPR {
    classes { FPR32: 32, FPR64: 64 }
    sub_register { FPR64 <: FPR32 }
    registers {
        xmm0 enc 0 names { xmm0: FPR32, xmm0: FPR64 }
    }
}

special {
    rip: 16
}
)";

    size_t m_sourceId{ 0 };
    std::optional<DSL::Ast::RegisterDef::RegisterFile> m_ast;
};

TEST_F(CppRegisterInfoGeneratorTest, EmitsFlatTablesWithEncodingsAndAliases)
{
    ASSERT_TRUE(parseAndRunPass(s_validRegisterFile));

    auto outHeader = m_testTempDir / "X86_64RegisterInfo.h";
    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), outHeader, "X86_64");
    ASSERT_TRUE(generator.run());
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    std::string content = readFileContent(outHeader);

    EXPECT_NE(content.find("Auto-generated by EzDSL CppRegisterInfoGenerator"), std::string::npos);
    EXPECT_NE(content.find("#pragma once"), std::string::npos);
    EXPECT_NE(content.find("namespace EzCodeEmitter::TableGen::X86_64"), std::string::npos);
    EXPECT_NE(content.find("struct RegisterInfoEntry"), std::string::npos);
    EXPECT_NE(content.find("uint32_t hwEncoding;"), std::string::npos);
    EXPECT_NE(content.find("struct SubRegEdge"), std::string::npos);
    EXPECT_NE(content.find("struct SpecialRegInfo"), std::string::npos);

    EXPECT_NE(content.find("RegisterInfoEntry{ \"GPR\", \"GPR64\", 64, 0, \"rax\" },"), std::string::npos);
    EXPECT_NE(content.find("RegisterInfoEntry{ \"GPR\", \"GPR8\", 8, 0, \"al\" },"), std::string::npos);
    EXPECT_NE(content.find("RegisterInfoEntry{ \"FPR\", \"FPR64\", 64, 0, \"xmm0\" },"), std::string::npos);

    EXPECT_NE(content.find("SubRegEdge{ \"GPR64\", \"rax\", \"GPR32\", \"eax\" },"), std::string::npos);
    EXPECT_NE(content.find("SubRegEdge{ \"FPR64\", \"xmm0\", \"FPR32\", \"xmm0\" },"), std::string::npos);

    EXPECT_NE(content.find("SpecialRegInfo{ \"rip\", 16 },"), std::string::npos);

    // The count entries must reflect the emitted tables.
    EXPECT_NE(content.find("s_registerEntryCount = 10;"), std::string::npos);
    EXPECT_NE(content.find("s_subRegEdgeCount = 7;"), std::string::npos);
    EXPECT_NE(content.find("s_specialRegCount = 1;"), std::string::npos);

    EXPECT_NE(content.find("getSpecialRegId"), std::string::npos);
    EXPECT_NE(content.find("initializeRegisterBanks"), std::string::npos);
    EXPECT_NE(content.find("addRegister(entry.asmName, entry.bitSize, 0, {}, entry.hwEncoding)"), std::string::npos);
    EXPECT_NE(content.find("parent->addSubPart(child)"), std::string::npos);
}

TEST_F(CppRegisterInfoGeneratorTest, SanitizesTargetNameForFileAndNamespace)
{
    ASSERT_TRUE(parseAndRunPass(s_validRegisterFile));

    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "x86-64");
    ASSERT_TRUE(generator.run());

    auto expectedFile = m_testTempDir / "x86_64RegisterInfo.h";
    ASSERT_TRUE(std::filesystem::exists(expectedFile));

    std::string content = readFileContent(expectedFile);
    EXPECT_NE(content.find("namespace EzCodeEmitter::TableGen::x86_64"), std::string::npos);
}

TEST_F(CppRegisterInfoGeneratorTest, EmitsValidEmptyHeaderForEmptySymbolTable)
{
    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "Empty");
    ASSERT_TRUE(generator.run());

    auto expectedFile = m_testTempDir / "EmptyRegisterInfo.h";
    ASSERT_TRUE(std::filesystem::exists(expectedFile));

    std::string content = readFileContent(expectedFile);
    EXPECT_NE(content.find("s_registerEntryCount = 0;"), std::string::npos);
    EXPECT_NE(content.find("SpecialRegInfo{ nullptr, 0 },"), std::string::npos);
}

TEST_F(CppRegisterInfoGeneratorTest, ConvenienceFunctionAndTimestampPreservation)
{
    ASSERT_TRUE(parseAndRunPass(s_validRegisterFile));

    auto outHeader = m_testTempDir / "X86_64RegisterInfo.h";
    ASSERT_TRUE(GenerateRegisterInfo(getDiagCollector(), getSymbolTable(), outHeader, "X86_64"));
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    auto pastTime = std::filesystem::last_write_time(outHeader) - std::chrono::seconds(5);
    std::filesystem::last_write_time(outHeader, pastTime);
    auto mtime1 = std::filesystem::last_write_time(outHeader);

    ASSERT_TRUE(GenerateRegisterInfo(getDiagCollector(), getSymbolTable(), outHeader, "X86_64"));
    auto mtime2 = std::filesystem::last_write_time(outHeader);
    EXPECT_EQ(mtime1, mtime2);
}

TEST_F(CppRegisterInfoGeneratorTest, FailsOnNullInputs)
{
    CppRegisterInfoGenerator genNullCollector(nullptr, getSymbolTable(), m_testTempDir, "X86_64");
    EXPECT_FALSE(genNullCollector.run());

    CppRegisterInfoGenerator genNullTable(getDiagCollector(), nullptr, m_testTempDir, "X86_64");
    EXPECT_FALSE(genNullTable.run());

    CppRegisterInfoGenerator genEmptyPath(getDiagCollector(), getSymbolTable(), "", "X86_64");
    EXPECT_FALSE(genEmptyPath.run());
}
