#include "EzDslCodeGeneratorsTestSuite.h"
#include "Ast/TargetDescDefLangAst.h"
#include "CodeGenerators/CppRegisterInfoGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Parser/ParseContext.h"
#include "Parser/TargetDescDefLang.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "Sema/Symbols/TargetDescSymbols.h"
#include "SemaPasses/TargetDescPass.h"

#include <chrono>
#include <filesystem>

using namespace CodeGenerators;

/**
 * Test fixture for the header-only register info generator.
 */
class CppRegisterInfoGeneratorTest : public EzDslCodeGeneratorsTestSuiteAsGtest
{
  protected:
    // Parses a target descriptor and runs the target descriptor semantic pass.
    bool parseAndRunPass(const std::string &source)
    {
        ParseContext ctx = createParseContextFromBuff(std::format("gen_reg_{}.tdesc", m_sourceId++), source);
        m_ast = ctx.parse<DSL::Parser::TargetDesc::TargetDescFileParser, DSL::Ast::TargetDesc::TargetDescFile>();
        if (!m_ast.has_value())
        {
            return false;
        }

        TargetDescPass pass;
        return pass.run(getDiagCollector(), getSymbolTable(), &m_ast.value());
    }

    static constexpr const char *s_validRegisterFile = R"(
target X86_64 {
    pointer_size: 8;
    stack_slot: 8;
    instruction_pointer: rip;
    object_formats: [ELF];
    default_calling_conv: C;

    register_bank GPR {
        classes { GPR8: 8, GPR16: 16, GPR32: 32, GPR64: 64 }
        sub_register { GPR16 <: GPR8, GPR32 <: GPR16, GPR64 <: GPR32 }
        registers {
            rax enc 0  names { rax: GPR64, eax: GPR32, ax: GPR16, al: GPR8 }
            rcx enc 1  names { rcx: GPR64, ecx: GPR32, cx: GPR16, cl: GPR8 }
        }
    }

    register_bank FPR {
        classes { FPR32: 32, FPR64: 64 }
        sub_register { FPR64 <: FPR32 }
        registers {
            xmm0 enc 0 names { xmm0: FPR32, xmm0: FPR64 }
        }
    }

    special {
        rip: 16
    }
}
)";

    size_t m_sourceId{ 0 };
    std::optional<DSL::Ast::TargetDesc::TargetDescFile> m_ast;
};

// Generates flat register tables and verifies encodings, aliases, special regs, and count constants.
TEST_F(CppRegisterInfoGeneratorTest, EmitsFlatTablesWithEncodingsAndAliases)
{
    ASSERT_TRUE(parseAndRunPass(s_validRegisterFile));

    auto outHeader = m_testTempDir / "X86_64RegisterInfo.h";
    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), outHeader, "X86_64");
    ASSERT_TRUE(generator.run());
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    std::string content = readFileContent(outHeader);

    EXPECT_NE(content.find("Auto-generated by EzDSL CppRegisterInfoGenerator"), std::string::npos);
    EXPECT_NE(content.find("#pragma once"), std::string::npos);
    EXPECT_NE(content.find("namespace EzTargets::TableGen::X86_64"), std::string::npos);
    EXPECT_NE(content.find("struct RegisterInfoEntry"), std::string::npos);
    EXPECT_NE(content.find("uint32_t hwEncoding;"), std::string::npos);
    EXPECT_NE(content.find("struct SubRegEdge"), std::string::npos);
    EXPECT_NE(content.find("struct SpecialRegInfo"), std::string::npos);

    EXPECT_NE(content.find("RegisterInfoEntry{ \"GPR\", \"GPR64\", 64, 0, \"rax\" },"), std::string::npos);
    EXPECT_NE(content.find("RegisterInfoEntry{ \"GPR\", \"GPR8\", 8, 0, \"al\" },"), std::string::npos);
    EXPECT_NE(content.find("RegisterInfoEntry{ \"FPR\", \"FPR64\", 64, 0, \"xmm0\" },"), std::string::npos);

    EXPECT_NE(content.find("SubRegEdge{ \"GPR64\", \"rax\", \"GPR32\", \"eax\" },"), std::string::npos);
    EXPECT_NE(content.find("SubRegEdge{ \"FPR64\", \"xmm0\", \"FPR32\", \"xmm0\" },"), std::string::npos);

    EXPECT_NE(content.find("SpecialRegInfo{ \"rip\", 16 },"), std::string::npos);

    // The count entries must reflect the emitted tables.
    EXPECT_NE(content.find("s_registerEntryCount = 10;"), std::string::npos);
    EXPECT_NE(content.find("s_subRegEdgeCount = 7;"), std::string::npos);
    EXPECT_NE(content.find("s_specialRegCount = 1;"), std::string::npos);

    EXPECT_NE(content.find("getSpecialRegId"), std::string::npos);
    EXPECT_NE(content.find("initializeRegisterBanks"), std::string::npos);
    EXPECT_NE(content.find("addRegister(entry.asmName, entry.bitSize, 0, {}, entry.hwEncoding)"), std::string::npos);
    EXPECT_NE(content.find("parent->addSubPart(child)"), std::string::npos);
}

// Verifies target names are sanitized for both the output file name and namespace.
TEST_F(CppRegisterInfoGeneratorTest, SanitizesTargetNameForFileAndNamespace)
{
    ASSERT_TRUE(parseAndRunPass(s_validRegisterFile));

    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "x86-64");
    ASSERT_TRUE(generator.run());

    auto expectedFile = m_testTempDir / "x86_64RegisterInfo.h";
    ASSERT_TRUE(std::filesystem::exists(expectedFile));

    std::string content = readFileContent(expectedFile);
    EXPECT_NE(content.find("namespace EzTargets::TableGen::x86_64"), std::string::npos);
}

// Verifies an empty symbol table still yields a valid header with zero counts.
TEST_F(CppRegisterInfoGeneratorTest, EmitsValidEmptyHeaderForEmptySymbolTable)
{
    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "Empty");
    ASSERT_TRUE(generator.run());

    auto expectedFile = m_testTempDir / "EmptyRegisterInfo.h";
    ASSERT_TRUE(std::filesystem::exists(expectedFile));

    std::string content = readFileContent(expectedFile);
    EXPECT_NE(content.find("s_registerEntryCount = 0;"), std::string::npos);
    EXPECT_NE(content.find("SpecialRegInfo{ nullptr, 0 },"), std::string::npos);
}

// Verifies the convenience entry point preserves the timestamp on unchanged regeneration.
TEST_F(CppRegisterInfoGeneratorTest, ConvenienceFunctionAndTimestampPreservation)
{
    ASSERT_TRUE(parseAndRunPass(s_validRegisterFile));

    auto outHeader = m_testTempDir / "X86_64RegisterInfo.h";
    ASSERT_TRUE(GenerateRegisterInfo(getDiagCollector(), getSymbolTable(), outHeader, "X86_64"));
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    auto pastTime = std::filesystem::last_write_time(outHeader) - std::chrono::seconds(5);
    std::filesystem::last_write_time(outHeader, pastTime);
    auto mtime1 = std::filesystem::last_write_time(outHeader);

    ASSERT_TRUE(GenerateRegisterInfo(getDiagCollector(), getSymbolTable(), outHeader, "X86_64"));
    auto mtime2 = std::filesystem::last_write_time(outHeader);
    EXPECT_EQ(mtime1, mtime2);
}

// Verifies generation fails for a null collector/table or an empty output path.
TEST_F(CppRegisterInfoGeneratorTest, FailsOnNullInputs)
{
    CppRegisterInfoGenerator genNullCollector(nullptr, getSymbolTable(), m_testTempDir, "X86_64");
    EXPECT_FALSE(genNullCollector.run());

    CppRegisterInfoGenerator genNullTable(getDiagCollector(), nullptr, m_testTempDir, "X86_64");
    EXPECT_FALSE(genNullTable.run());

    CppRegisterInfoGenerator genEmptyPath(getDiagCollector(), getSymbolTable(), "", "X86_64");
    EXPECT_FALSE(genEmptyPath.run());
}

// Verifies the production x86_64.tdesc manifest parses, passes Sema, and generates complete register tables.
TEST_F(CppRegisterInfoGeneratorTest, ParsesAndGeneratesRealX86_64Registers)
{
    std::filesystem::path manifestPath;
    std::filesystem::path current = std::filesystem::current_path();
    for (int i = 0; i < 6; ++i)
    {
        auto candidate = current / "EzTargets" / "X86_64" / "targets" / "x86_64" / "x86_64.tdesc";
        if (std::filesystem::exists(candidate))
        {
            manifestPath = candidate;
            break;
        }
        if (current.has_parent_path() && current != current.parent_path())
        {
            current = current.parent_path();
        }
    }
    ASSERT_FALSE(manifestPath.empty()) << "Could not find x86_64.tdesc from cwd " << std::filesystem::current_path();

    std::string content = readFileContent(manifestPath);
    ASSERT_TRUE(parseAndRunPass(content));

    auto outHeader = m_testTempDir / "x86_64RegisterInfo.h";
    CppRegisterInfoGenerator generator(getDiagCollector(), getSymbolTable(), outHeader, "x86_64");
    ASSERT_TRUE(generator.run());
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    std::string header = readFileContent(outHeader);

    EXPECT_NE(header.find("namespace EzTargets::TableGen::x86_64"), std::string::npos);
    EXPECT_NE(header.find("s_registerEntryCount = 112;"), std::string::npos);
    EXPECT_NE(header.find("s_subRegEdgeCount = 80;"), std::string::npos);
    EXPECT_NE(header.find("s_specialRegCount = 1;"), std::string::npos);

    // GPR checks
    EXPECT_NE(header.find("RegisterInfoEntry{ \"GPR\", \"GPR64\", 64, 0, \"rax\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"GPR\", \"GPR32\", 32, 0, \"eax\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"GPR\", \"GPR16\", 16, 0, \"ax\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"GPR\", \"GPR8\", 8, 0, \"al\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"GPR\", \"GPR64\", 64, 15, \"r15\" },"), std::string::npos);

    // FPR checks
    EXPECT_NE(header.find("RegisterInfoEntry{ \"FPR\", \"FPR32\", 32, 0, \"xmm0\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"FPR\", \"FPR64\", 64, 0, \"xmm0\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"FPR\", \"VR128\", 128, 0, \"xmm0\" },"), std::string::npos);
    EXPECT_NE(header.find("RegisterInfoEntry{ \"FPR\", \"VR128\", 128, 15, \"xmm15\" },"), std::string::npos);

    // Sub-register edge checks
    EXPECT_NE(header.find("SubRegEdge{ \"GPR64\", \"rax\", \"GPR32\", \"eax\" },"), std::string::npos);
    EXPECT_NE(header.find("SubRegEdge{ \"VR128\", \"xmm0\", \"FPR64\", \"xmm0\" },"), std::string::npos);
    EXPECT_NE(header.find("SubRegEdge{ \"FPR64\", \"xmm0\", \"FPR32\", \"xmm0\" },"), std::string::npos);

    // Special register
    EXPECT_NE(header.find("SpecialRegInfo{ \"rip\", 16 },"), std::string::npos);
    EXPECT_NE(header.find("initializeRegisterBanks"), std::string::npos);
    EXPECT_NE(header.find("getSpecialRegId"), std::string::npos);
}
