#include "EzDslCodeGeneratorsTestSuite.h"
#include "Ast/IrInstructionDefLangAst.h"
#include "CodeGenerators/CppMirInstructionGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Parser/IrInstructionDefLang.h"
#include "Parser/ParseContext.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "SemaPasses/IrInstructionPass.h"

#include <chrono>
#include <filesystem>

using namespace CodeGenerators;

/**
 * Fixture for generating the C++ instruction-set definitions from IR-instruction DSL sources.
 */
class CppMirInstructionGeneratorTest : public EzDslCodeGeneratorsTestSuiteAsGtest
{
  protected:
    // Parses an IR-instruction source and runs the IR-instruction semantic pass.
    bool parseAndRunPass(const std::string &source)
    {
        auto ast = parseIrInstDefFile(source);
        if (!ast.has_value())
        {
            return false;
        }

        IrInstructionPass instPass;
        return instPass.run(getDiagCollector(), getSymbolTable(), &ast.value());
    }

    // Declares an IR instruction symbol directly, bypassing the DSL, for generator tests.
    void declareRawInstruction(std::string_view name,
                               DSL::Ast::IrInstDef::IrInstCategory category,
                               DSL::Ast::IrInstDef::IrInstTier tier,
                               DSL::Ast::IrInstDef::IrInstFlag flags,
                               std::vector<Symbols::IrOperandSymbol> operands = {})
    {
        std::pmr::vector<Symbols::IrOperandSymbol> pmrOperands(getAllocator());
        pmrOperands.reserve(operands.size());
        for (auto &op : operands)
        {
            pmrOperands.push_back(op);
        }

        Symbols::IrInstructionSymbol instSym{ .m_name = std::string(name),
                                              .m_category = category,
                                              .m_tier = tier,
                                              .m_flags = flags,
                                              .m_operands = std::move(pmrOperands) };

        getSymbolTable()->declareSym(nullptr, SymbolType::IrInstruction, std::move(instSym), name);
    }
};

// ============================================================================
// 1. Positive Integration Tests (Via DSL Parsing & Pass)
// ============================================================================

TEST_F(CppMirInstructionGeneratorTest, TestStandardInstructionSetGeneration)
{
    std::string irSource = R"(
        ir_inst Add ( Register:dst OUT, Register:lhs IN, Register:rhs IN ) {
            CATEGORY(Arithmetic);
            TIER(HighLevel);
            FLAGS(IsCommutative, SizeMatch);
        };

        ir_inst Nop () {
            CATEGORY(System);
            TIER(HighLevel);
        };

        ir_inst Branch ( AddressSource:target IN ) {
            CATEGORY(ControlFlow);
            TIER(HighLevel);
            FLAGS(IsBranch, IsTerminator);
        };

        ir_inst Ret () {
            CATEGORY(ControlFlow);
            TIER(HighLevel);
            FLAGS(IsReturn, IsTerminator);
        };
    )";

    ASSERT_TRUE(parseAndRunPass(irSource));

    auto outHeader = m_testTempDir / "MirInstructionSetDefs.h";
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), outHeader);
    ASSERT_TRUE(generator.run());
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    std::string content = readFileContent(outHeader);

    // 1. Banner and guards
    EXPECT_TRUE(content.find("Auto-generated by EzDSL CppMirInstructionGenerator") != std::string::npos);
    EXPECT_TRUE(content.find("#ifdef INSTRUCTION") != std::string::npos);
    EXPECT_TRUE(content.find("#define OPERAND_CONSTRAINTS(...)") != std::string::npos);

    // 2. gtest collision protection
    EXPECT_TRUE(content.find("#ifdef TEST") != std::string::npos);
    EXPECT_TRUE(content.find("#pragma push_macro(\"TEST\")") != std::string::npos);
    EXPECT_TRUE(content.find("#pragma pop_macro(\"TEST\")") != std::string::npos);

    // 3. INVALID instruction
    EXPECT_TRUE(content.find("INSTRUCTION(INVALID, T(HighLevel), MirCat_Invalid, OPERAND_CONSTRAINTS(), F(None))") !=
                std::string::npos);

    // 4. Zero-operand instruction (Nop)
    EXPECT_TRUE(content.find("INSTRUCTION(Nop, T(HighLevel), MirCat_System, OPERAND_CONSTRAINTS(), F(None))") !=
                std::string::npos);

    // 5. Single-operand instruction (Branch)
    EXPECT_TRUE(content.find("INSTRUCTION(Branch,") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_ControlFlow") != std::string::npos);
    EXPECT_TRUE(content.find("OPERAND_CONSTRAINTS({ ExpectedOperandType::AddressSource, MirOperandFlag::Read })") !=
                std::string::npos);
    EXPECT_TRUE(content.find("F(IsTerminator) | F(IsBranch)") != std::string::npos);

    // 6. Three-operand ALU instruction (Add)
    EXPECT_TRUE(content.find("INSTRUCTION(Add,") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Arithmetic") != std::string::npos);
    EXPECT_TRUE(content.find("{ ExpectedOperandType::Register, MirOperandFlag::Write }") != std::string::npos);
    EXPECT_TRUE(content.find("{ ExpectedOperandType::Register, MirOperandFlag::Read }") != std::string::npos);
    EXPECT_TRUE(content.find("F(SizeMatch) | F(IsCommutative)") != std::string::npos);

    // 7. Undef cleanup
    EXPECT_TRUE(content.find("#undef T") != std::string::npos);
    EXPECT_TRUE(content.find("#undef F") != std::string::npos);
    EXPECT_TRUE(content.find("#undef OPERAND_CONSTRAINTS") != std::string::npos);
    EXPECT_TRUE(content.find("#endif // INSTRUCTION") != std::string::npos);
}

// ============================================================================
// 2. Comprehensive Operand Types and Directions
// ============================================================================

TEST_F(CppMirInstructionGeneratorTest, TestAllOperandTypesAndDirections)
{
    using namespace DSL::Ast::IrInstDef;

    std::vector<Symbols::IrOperandSymbol> operands = {
        { .m_type = IrOperandType::Register, .m_name = "op_reg", .m_dir = IrOperandDir::ArgOut },
        { .m_type = IrOperandType::Integer, .m_name = "op_int", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::FloatingPoint, .m_name = "op_fp", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::Memory, .m_name = "op_mem", .m_dir = IrOperandDir::ArgInOut },
        { .m_type = IrOperandType::Reference, .m_name = "op_ref", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::RuntimeSymbol, .m_name = "op_sym", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::VariadicArgs, .m_name = "op_var", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::Immediate, .m_name = "op_imm", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::RegIntImm, .m_name = "op_reg_int", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::RegFloatImm, .m_name = "op_reg_fp", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::RegImm, .m_name = "op_reg_imm", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::AddressSource, .m_name = "op_addr", .m_dir = IrOperandDir::ArgIn },
        { .m_type = IrOperandType::Any, .m_name = "op_any", .m_dir = IrOperandDir::ArgIn },
    };

    declareRawInstruction("ComplexInst",
                          IrInstCategory::DataMovement,
                          IrInstTier::HighLevel,
                          IrInstFlag::None,
                          std::move(operands));

    auto outHeader = m_testTempDir / "ComplexDefs.h";
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), outHeader);
    ASSERT_TRUE(generator.run());

    std::string content = readFileContent(outHeader);

    EXPECT_TRUE(content.find("ExpectedOperandType::Register, MirOperandFlag::Write") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::Integer, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::FloatingPoint, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::Memory, MirOperandFlag::ReadWrite") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::Reference, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::RuntimeSymbol, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::VariadicArgs, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::Immediate, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::RegIntImm, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::RegFloatImm, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::RegImm, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::AddressSource, MirOperandFlag::Read") != std::string::npos);
    EXPECT_TRUE(content.find("ExpectedOperandType::Any, MirOperandFlag::Read") != std::string::npos);
}

// ============================================================================
// 3. Comprehensive Categories, Tiers, and Flags
// ============================================================================

TEST_F(CppMirInstructionGeneratorTest, TestAllCategoriesAndTiers)
{
    using namespace DSL::Ast::IrInstDef;

    declareRawInstruction("InstDataMov", IrInstCategory::DataMovement, IrInstTier::HighLevel, IrInstFlag::None);
    declareRawInstruction("InstMemory", IrInstCategory::Memory, IrInstTier::PassInternal, IrInstFlag::ReadsMemory);
    declareRawInstruction("InstArithmetic", IrInstCategory::Arithmetic, IrInstTier::TargetLow, IrInstFlag::None);
    declareRawInstruction("InstBitwise", IrInstCategory::Bitwise, IrInstTier::HighLevel, IrInstFlag::None);
    declareRawInstruction("InstCompare", IrInstCategory::Compare, IrInstTier::HighLevel, IrInstFlag::ReadsCPUFlags);
    declareRawInstruction("InstControlFlow", IrInstCategory::ControlFlow, IrInstTier::HighLevel, IrInstFlag::IsBranch);
    declareRawInstruction("InstCasting", IrInstCategory::Casting, IrInstTier::HighLevel, IrInstFlag::DestLarger);
    declareRawInstruction("InstSystem", IrInstCategory::System, IrInstTier::HighLevel, IrInstFlag::HasSideEffect);
    declareRawInstruction("InstVector", IrInstCategory::Vector, IrInstTier::HighLevel, IrInstFlag::None);

    auto outHeader = m_testTempDir / "CategoriesDefs.h";
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), outHeader);
    ASSERT_TRUE(generator.run());

    std::string content = readFileContent(outHeader);

    // Verify categories
    EXPECT_TRUE(content.find("MirCat_DataMovement") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Memory") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Arithmetic") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Bitwise") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Compare") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_ControlFlow") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Casting") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_System") != std::string::npos);
    EXPECT_TRUE(content.find("MirCat_Vector") != std::string::npos);

    // Verify tiers
    EXPECT_TRUE(content.find("T(HighLevel)") != std::string::npos);
    EXPECT_TRUE(content.find("T(PassInternal)") != std::string::npos);
    EXPECT_TRUE(content.find("T(TargetLow)") != std::string::npos);
}

// Verifies the None flag and a combined multi-flag mask render correctly in the generated definitions.
TEST_F(CppMirInstructionGeneratorTest, TestCombinedFlagsAndNoneFlag)
{
    using namespace DSL::Ast::IrInstDef;

    // None flag
    declareRawInstruction("InstNoFlags", IrInstCategory::System, IrInstTier::HighLevel, IrInstFlag::None);

    // Combined multi-flags
    auto multiFlags = IrInstFlag::ReadsMemory | IrInstFlag::WritesMemory | IrInstFlag::HasSideEffect |
            IrInstFlag::WritesCPUFlags | IrInstFlag::TreatAsSigned;
    declareRawInstruction("InstMultiFlags", IrInstCategory::Memory, IrInstTier::HighLevel, multiFlags);

    auto outHeader = m_testTempDir / "FlagsDefs.h";
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), outHeader);
    ASSERT_TRUE(generator.run());

    std::string content = readFileContent(outHeader);

    EXPECT_TRUE(content.find("INSTRUCTION(InstNoFlags, T(HighLevel), MirCat_System, OPERAND_CONSTRAINTS(), F(None))") !=
                std::string::npos);

    EXPECT_TRUE(content.find(
                        "F(ReadsMemory) | F(WritesMemory) | F(HasSideEffect) | F(WritesCPUFlags) | F(TreatAsSigned)") !=
                std::string::npos);
}

// ============================================================================
// 4. Convenience Function & Timestamp Preservation
// ============================================================================

TEST_F(CppMirInstructionGeneratorTest, TestConvenienceFunctionAndMtimePreservation)
{
    using namespace DSL::Ast::IrInstDef;
    declareRawInstruction("InstA", IrInstCategory::Arithmetic, IrInstTier::HighLevel, IrInstFlag::None);

    auto outHeader = m_testTempDir / "Defs.h";

    // Run via convenience function
    EXPECT_TRUE(GenerateMirIrInstructionDefs(getDiagCollector(), getSymbolTable(), outHeader));
    EXPECT_TRUE(std::filesystem::exists(outHeader));

    auto pastTime = std::filesystem::last_write_time(outHeader) - std::chrono::seconds(5);
    std::filesystem::last_write_time(outHeader, pastTime);
    auto mtime1 = std::filesystem::last_write_time(outHeader);

    // Running again with identical symbols should preserve mtime
    EXPECT_TRUE(GenerateMirIrInstructionDefs(getDiagCollector(), getSymbolTable(), outHeader));
    auto mtime2 = std::filesystem::last_write_time(outHeader);
    EXPECT_EQ(mtime1, mtime2);
}

// ============================================================================
// 5. Negative and Edge Cases
// ============================================================================

TEST_F(CppMirInstructionGeneratorTest, TestEmptySymbolTableGeneratesValidHeader)
{
    // Empty SymbolTable has 0 instructions
    auto outHeader = m_testTempDir / "EmptyDefs.h";
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), outHeader);
    EXPECT_TRUE(generator.run());
    EXPECT_TRUE(std::filesystem::exists(outHeader));

    std::string content = readFileContent(outHeader);
    // Should contain INVALID instruction and macro wrappers
    EXPECT_TRUE(content.find("INSTRUCTION(INVALID, T(HighLevel), MirCat_Invalid, OPERAND_CONSTRAINTS(), F(None))") !=
                std::string::npos);
}

// Verifies type symbols in the table are not emitted as instructions.
TEST_F(CppMirInstructionGeneratorTest, TestIgnoresNonInstructionSymbols)
{
    // Declare type symbols into the table
    registerType("i32", DSL::Ast::TypeDef::TypeKind::Integer, 32, 32, 1);
    registerType("f64", DSL::Ast::TypeDef::TypeKind::FloatingPoint, 64, 64, 2);

    auto outHeader = m_testTempDir / "NonInstDefs.h";
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), outHeader);
    EXPECT_TRUE(generator.run());

    std::string content = readFileContent(outHeader);
    // Ensure type symbols were not generated as instructions
    EXPECT_TRUE(content.find("INSTRUCTION(i32") == std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(f64") == std::string::npos);
}

// Verifies generation fails for a null collector/table or an empty output path.
TEST_F(CppMirInstructionGeneratorTest, TestNullPointersAndEmptyPathFailValidation)
{
    CppMirInstructionGenerator genNullCollector(nullptr, getSymbolTable(), m_testTempDir);
    EXPECT_FALSE(genNullCollector.run());

    CppMirInstructionGenerator genNullTable(getDiagCollector(), nullptr, m_testTempDir);
    EXPECT_FALSE(genNullTable.run());

    CppMirInstructionGenerator genEmptyPath(getDiagCollector(), getSymbolTable(), "");
    EXPECT_FALSE(genEmptyPath.run());
}

// Verifies a directory output path gets the default MirInstructionSetDefs.h file name appended.
TEST_F(CppMirInstructionGeneratorTest, TestDirectoryPathAppendsDefaultFilename)
{
    declareRawInstruction("InstDir",
                          DSL::Ast::IrInstDef::IrInstCategory::System,
                          DSL::Ast::IrInstDef::IrInstTier::HighLevel,
                          DSL::Ast::IrInstDef::IrInstFlag::None);

    // Pass directory path
    CppMirInstructionGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir);
    EXPECT_TRUE(generator.run());

    // Expect MirInstructionSetDefs.h created inside directory
    auto expectedFile = m_testTempDir / "MirInstructionSetDefs.h";
    EXPECT_TRUE(std::filesystem::exists(expectedFile));
}
