#include "EzDslCodeGeneratorsTestSuite.h"
#include "Ast/TargetDescDefLangAst.h"
#include "CodeGenerators/CppTargetDescGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Parser/ParseContext.h"
#include "Parser/TargetDescDefLang.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "SemaPasses/TargetDescPass.h"

#include <chrono>
#include <filesystem>

using namespace CodeGenerators;

/**
 * Test fixture for the target descriptor generator.
 */
class CppTargetDescGeneratorTest : public EzDslCodeGeneratorsTestSuiteAsGtest
{
  protected:
    // Parses a target descriptor and runs the target-descriptor semantic pass.
    bool parseAndRunPass(const std::string &source)
    {
        ParseContext ctx = createParseContextFromBuff(std::format("gen_tdesc_{}.tdesc", m_sourceId++), source);
        m_ast = ctx.parse<DSL::Parser::TargetDesc::TargetDescFileParser, DSL::Ast::TargetDesc::TargetDescFile>();
        if (!m_ast.has_value())
        {
            return false;
        }

        TargetDescPass pass;
        return pass.run(getDiagCollector(), getSymbolTable(), &m_ast.value());
    }

    static constexpr const char *s_validManifest = R"(
target X86_64 {
    registers:     "x86_64_registers.reg";
    instructions:  "x86_64_instructions.idf";
    calling_convs: ["x86_64_calling_conv.ezcc"];

    pointer_size: 8;
    stack_slot:   8;

    instruction_pointer: rip;
    mem_disp_type: i64;

    object_formats: [ELF, COFF];
    default_calling_conv: SysV_AMD64;

    libcalls {
        __returnNothing: "__returnNothing";
        __divdi3: "__divdi3";
        __udivdi3: "__udivdi3"
    }

    components {
        frame_lowerer: X86_64FrameLowerer;
        instruction_selector: X86_64TargetInstructionSelector;
        register_allocator: X86_64RegisterAllocator
    }
}
)";

    size_t m_sourceId{ 0 };
    std::optional<DSL::Ast::TargetDesc::TargetDescFile> m_ast;
};

// Generates a target descriptor header/source and verifies metadata, object formats, libcalls, and component counts.
TEST_F(CppTargetDescGeneratorTest, EmitsTargetDescriptorHeaderAndSource)
{
    ASSERT_TRUE(parseAndRunPass(s_validManifest));

    CppTargetDescGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "X86_64");
    ASSERT_TRUE(generator.run());

    auto headerPath = m_testTempDir / "X86_64TargetDesc.h";
    auto sourcePath = m_testTempDir / "X86_64TargetDesc.cpp";
    ASSERT_TRUE(std::filesystem::exists(headerPath));
    ASSERT_TRUE(std::filesystem::exists(sourcePath));

    std::string header = readFileContent(headerPath);
    std::string source = readFileContent(sourcePath);

    EXPECT_NE(header.find("Auto-generated by EzDSL CppTargetDescGenerator"), std::string::npos);
    EXPECT_NE(header.find("namespace EzTargets::TableGen::X86_64"), std::string::npos);
    EXPECT_NE(header.find("class X86_64TargetDesc : public TargetDesc"), std::string::npos);
    EXPECT_NE(header.find("const char *getName() const override { return \"X86_64\"; }"), std::string::npos);
    EXPECT_NE(header.find("size_t getStackSlotSize() const override { return 8; }"), std::string::npos);
    EXPECT_NE(header.find("inline constexpr const char *s_objectFormats[] ="), std::string::npos);
    EXPECT_NE(header.find("\"ELF\","), std::string::npos);
    EXPECT_NE(header.find("\"COFF\","), std::string::npos);
    EXPECT_NE(header.find("s_objectFormatsCount = 2;"), std::string::npos);
    EXPECT_NE(header.find("s_componentSlotCount = 3;"), std::string::npos);
    EXPECT_NE(header.find("s_componentTypeCount = 3;"), std::string::npos);
    EXPECT_NE(header.find("s_libcallCount = 3;"), std::string::npos);

    EXPECT_NE(source.find("#include \"X86_64TargetDesc.h\""), std::string::npos);
    EXPECT_NE(source.find("#include \"X86_64RegisterInfo.h\""), std::string::npos);
    EXPECT_NE(source.find("initializeRegisterBanks(m_ctx->getGlobalAllocator())"), std::string::npos);
    EXPECT_NE(source.find("getSpecialRegId(\"rip\")"), std::string::npos);
    EXPECT_NE(source.find("case 0: return \"__returnNothing\";"), std::string::npos);
    EXPECT_NE(source.find("case 2: return \"__udivdi3\";"), std::string::npos);
    EXPECT_NE(source.find("MirRegisterBank *X86_64TargetDesc::createRegisterBank(const char *name)"),
              std::string::npos);
}

// Verifies non-identifier target names are sanitized for file names and namespaces.
TEST_F(CppTargetDescGeneratorTest, SanitizesTargetName)
{
    ASSERT_TRUE(parseAndRunPass(s_validManifest));

    CppTargetDescGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "x86-64");
    ASSERT_TRUE(generator.run());

    ASSERT_TRUE(std::filesystem::exists(m_testTempDir / "x86_64TargetDesc.h"));
    ASSERT_TRUE(std::filesystem::exists(m_testTempDir / "x86_64TargetDesc.cpp"));

    std::string header = readFileContent(m_testTempDir / "x86_64TargetDesc.h");
    EXPECT_NE(header.find("namespace EzTargets::TableGen::x86_64"), std::string::npos);
    EXPECT_NE(header.find("class x86_64TargetDesc : public TargetDesc"), std::string::npos);
}

// Verifies generation creates and writes both files into a nested output directory.
TEST_F(CppTargetDescGeneratorTest, WritesIntoNestedOutputDirectory)
{
    ASSERT_TRUE(parseAndRunPass(s_validManifest));

    {
        CppTargetDescGenerator headerGen(getDiagCollector(), getSymbolTable(), m_testTempDir / "OnlyH", "X86_64");
        ASSERT_TRUE(headerGen.run());
        EXPECT_TRUE(std::filesystem::exists(m_testTempDir / "OnlyH" / "X86_64TargetDesc.h"));
        EXPECT_TRUE(std::filesystem::exists(m_testTempDir / "OnlyH" / "X86_64TargetDesc.cpp"));
    }
}

// Verifies the convenience entry point regenerates without changing the timestamp when content is unchanged.
TEST_F(CppTargetDescGeneratorTest, ConvenienceFunctionAndTimestampPreservation)
{
    ASSERT_TRUE(parseAndRunPass(s_validManifest));

    auto outHeader = m_testTempDir / "X86_64TargetDesc.h";
    ASSERT_TRUE(GenerateTargetDescriptor(getDiagCollector(), getSymbolTable(), outHeader, "X86_64"));
    ASSERT_TRUE(std::filesystem::exists(outHeader));

    auto pastTime = std::filesystem::last_write_time(outHeader) - std::chrono::seconds(5);
    std::filesystem::last_write_time(outHeader, pastTime);
    auto mtime1 = std::filesystem::last_write_time(outHeader);

    ASSERT_TRUE(GenerateTargetDescriptor(getDiagCollector(), getSymbolTable(), outHeader, "X86_64"));
    auto mtime2 = std::filesystem::last_write_time(outHeader);
    EXPECT_EQ(mtime1, mtime2);
}

// Verifies generation fails with a missing target symbol, a null collector, or a null symbol table.
TEST_F(CppTargetDescGeneratorTest, FailsWithoutTargetSymbolAndOnNullInputs)
{
    // Empty symbol table: no target descriptor symbol.
    CppTargetDescGenerator genEmpty(getDiagCollector(), getSymbolTable(), m_testTempDir, "X86_64");
    EXPECT_FALSE(genEmpty.run());

    CppTargetDescGenerator genNullCollector(nullptr, getSymbolTable(), m_testTempDir, "X86_64");
    EXPECT_FALSE(genNullCollector.run());

    CppTargetDescGenerator genNullTable(getDiagCollector(), nullptr, m_testTempDir, "X86_64");
    EXPECT_FALSE(genNullTable.run());
}

// Verifies target extensions declared in the manifest are emitted into tables and registered in the constructor.
TEST_F(CppTargetDescGeneratorTest, EmitsTargetExtensions)
{
    std::string manifestWithExt = R"(
target X86_64 {
    pointer_size: 8;
    stack_slot:   8;
    object_formats: [ELF];
    default_calling_conv: SysV_AMD64;

    extensions {
        sse {
            default: true;
            description: "Streaming SIMD Extensions";
        };
        sse2 {
            default: true;
            implies: [sse];
        };
        avx {
            implies: [sse2];
            description: "Advanced Vector Extensions";
        };
    }
}
)";

    ASSERT_TRUE(parseAndRunPass(manifestWithExt));

    CppTargetDescGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir, "X86_64");
    ASSERT_TRUE(generator.run());

    auto headerPath = m_testTempDir / "X86_64TargetDesc.h";
    auto sourcePath = m_testTempDir / "X86_64TargetDesc.cpp";
    ASSERT_TRUE(std::filesystem::exists(headerPath));
    ASSERT_TRUE(std::filesystem::exists(sourcePath));

    std::string header = readFileContent(headerPath);
    std::string source = readFileContent(sourcePath);

    EXPECT_NE(header.find("inline constexpr const char *s_targetExtensions[] ="), std::string::npos);
    EXPECT_NE(header.find("\"sse\","), std::string::npos);
    EXPECT_NE(header.find("\"sse2\","), std::string::npos);
    EXPECT_NE(header.find("\"avx\","), std::string::npos);
    EXPECT_NE(header.find("s_targetExtensionCount = 3;"), std::string::npos);

    EXPECT_NE(source.find("m_extensions.registerExtension(\"sse\", \"Streaming SIMD Extensions\", true, {})"), std::string::npos);
    EXPECT_NE(source.find("m_extensions.registerExtension(\"sse2\", \"\", true, {\"sse\"})"), std::string::npos);
    EXPECT_NE(source.find("m_extensions.registerExtension(\"avx\", \"Advanced Vector Extensions\", false, {\"sse2\"})"), std::string::npos);
}

