#include "EzDslCodeGeneratorsTestSuite.h"
#include "Ast/TypeDefLangAst.h"
#include "CodeGenerators/CppMirTypeTableGenerator.h"
#include "Diagnostics/DiagnosticCollector.h"
#include "Parser/ParseContext.h"
#include "Parser/TypeDefLang.h"
#include "Sema/Symbol.h"
#include "Sema/SymbolTable.h"
#include "SemaPasses/TypePass.h"

#include <chrono>
#include <filesystem>

using namespace CodeGenerators;

class CppMirTypeTableGeneratorTest : public EzDslCodeGeneratorsTestSuiteAsGtest
{
  protected:
    bool parseAndRunPass(const std::string &source)
    {
        auto ast = parseTypeDefFile(source);
        if (!ast.has_value())
        {
            return false;
        }

        TypePass typePass;
        return typePass.run(getDiagCollector(), getSymbolTable(), &ast.value());
    }
};

// ============================================================================
// 1. Positive Integration Tests (Via DSL Parsing & Pass)
// ============================================================================

TEST_F(CppMirTypeTableGeneratorTest, TestStandardTypeTableGenerationViaDsl)
{
    std::string typeSource = R"(
        integer i1(1);
        integer i8(8);
        integer i32(32);
        float f32(32);
        float f64(64);
        void v();
        pointer ptr();
    )";

    ASSERT_TRUE(parseAndRunPass(typeSource));

    CppMirTypeTableGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir);
    ASSERT_TRUE(generator.run());

    auto headerPath = m_testTempDir / "MirTypeTable.h";
    auto sourcePath = m_testTempDir / "MirTypeTable.cpp";

    ASSERT_TRUE(std::filesystem::exists(headerPath));
    ASSERT_TRUE(std::filesystem::exists(sourcePath));

    // --- Verify Header Content ---
    std::string hContent = readFileContent(headerPath);

    // 1. Guards, Banners, Includes
    EXPECT_TRUE(hContent.find("#ifndef EZMIR_MIR_TYPE_TABLE_H") != std::string::npos);
    EXPECT_TRUE(hContent.find("#define EZMIR_MIR_TYPE_TABLE_H") != std::string::npos);
    EXPECT_TRUE(hContent.find("Auto-generated by EzDSL CppMirTypeTableGenerator") != std::string::npos);
    EXPECT_TRUE(hContent.find("#include \"Type/MirType.h\"") != std::string::npos);

    // 2. MirTypeCompactId Enum (excludes ptr)
    EXPECT_TRUE(hContent.find("enum class MirTypeCompactId : uint8_t") != std::string::npos);
    EXPECT_TRUE(hContent.find("Invalid = 0,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i1 = 1,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i8 = 2,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i32 = 3,") != std::string::npos);
    EXPECT_TRUE(hContent.find("f32 = 4,") != std::string::npos);
    EXPECT_TRUE(hContent.find("f64 = 5,") != std::string::npos);
    EXPECT_TRUE(hContent.find("v = 6,") != std::string::npos);
    EXPECT_TRUE(hContent.find("Custom = 255") != std::string::npos);
    EXPECT_TRUE(hContent.find("ptr =") == std::string::npos);

    // 3. MachineTypeCount (6 primitive types, excluding ptr)
    EXPECT_TRUE(hContent.find("constexpr size_t MachineTypeCount = 6;") != std::string::npos);

    // 4. MirTypeTable Class Declarations & Accessors
    EXPECT_TRUE(hContent.find("class MirTypeTable") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i32();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *f64();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *m_i32Type{ nullptr };") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *m_f64Type{ nullptr };") != std::string::npos);
    EXPECT_TRUE(hContent.find("void initialize(size_t pointerBitWidth);") != std::string::npos);

    // --- Verify Source Content ---
    std::string sContent = readFileContent(sourcePath);

    EXPECT_TRUE(sContent.find("MirTypeTable::MirTypeTable(std::pmr::memory_resource *globalArena, size_t pointerBitWidth) :") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("m_compactIdToType.fill(nullptr);") != std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::create(") != std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::getFuncType(") != std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::getPtr(MirType *srcType)") != std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::getArray(MirType *elementType, size_t elementCount)") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::getFloatingTypeBySize(size_t sizeInBits) const") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::getIntegerTypeBySize(size_t sizeInBits) const") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::i32() { return m_i32Type; }") != std::string::npos);
    EXPECT_TRUE(sContent.find("void MirTypeTable::initialize(size_t pointerBitWidth)") != std::string::npos);
    EXPECT_TRUE(sContent.find("m_i32Type = create(MirTypeKind::Integer, 32, 32, {}, \"i32\", 3);") != std::string::npos);
    EXPECT_TRUE(sContent.find("m_f64Type = create(MirTypeKind::FloatingPoint, 64, 64, {}, \"f64\", 5);") !=
                std::string::npos);
}

// ============================================================================
// 2. Working Modes (Header-only, Source-only, Full) & Bitwise Operators
// ============================================================================

TEST_F(CppMirTypeTableGeneratorTest, TestWorkingModes)
{
    registerType("i32", DSL::Ast::TypeDef::TypeKind::Integer, 32, 32, 1);

    // 1. Bitwise operator assertions
    auto fullMode = MirTypeTableGenWorkingMode::Header | MirTypeTableGenWorkingMode::Source;
    EXPECT_EQ(fullMode, MirTypeTableGenWorkingMode::Full);
    EXPECT_TRUE(fullMode & MirTypeTableGenWorkingMode::Header);
    EXPECT_TRUE(fullMode & MirTypeTableGenWorkingMode::Source);

    // 2. Header-only generation
    auto headerOnlyDir = m_testTempDir / "header_only";
    std::filesystem::create_directories(headerOnlyDir);
    CppMirTypeTableGenerator genHeaderOnly(getDiagCollector(),
                                          getSymbolTable(),
                                          headerOnlyDir,
                                          MirTypeTableGenWorkingMode::Header);
    EXPECT_TRUE(genHeaderOnly.run());
    EXPECT_TRUE(std::filesystem::exists(headerOnlyDir / "MirTypeTable.h"));
    EXPECT_FALSE(std::filesystem::exists(headerOnlyDir / "MirTypeTable.cpp"));

    // 3. Source-only generation
    auto sourceOnlyDir = m_testTempDir / "source_only";
    std::filesystem::create_directories(sourceOnlyDir);
    CppMirTypeTableGenerator genSourceOnly(getDiagCollector(),
                                          getSymbolTable(),
                                          sourceOnlyDir,
                                          MirTypeTableGenWorkingMode::Source);
    EXPECT_TRUE(genSourceOnly.run());
    EXPECT_FALSE(std::filesystem::exists(sourceOnlyDir / "MirTypeTable.h"));
    EXPECT_TRUE(std::filesystem::exists(sourceOnlyDir / "MirTypeTable.cpp"));
}

// ============================================================================
// 3. All Type Kinds (Void, Integer, Float, BindingToken, Pointer)
// ============================================================================

TEST_F(CppMirTypeTableGeneratorTest, TestAllTypeKindsAndKindToEnumString)
{
    using namespace DSL::Ast::TypeDef;

    registerType("my_void", TypeKind::Void, 0, 0, 1);
    registerType("my_int", TypeKind::Integer, 32, 32, 2);
    registerType("my_float", TypeKind::FloatingPoint, 64, 64, 3);
    registerType("my_token", TypeKind::BindingToken, 0, 0, 4);
    registerType("my_ptr", TypeKind::Pointer, 64, 64, 5);

    CppMirTypeTableGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir);
    ASSERT_TRUE(generator.run());

    std::string sContent = readFileContent(m_testTempDir / "MirTypeTable.cpp");

    EXPECT_TRUE(sContent.find("create(MirTypeKind::Void, 0, 0, {}, \"my_void\", 1)") != std::string::npos);
    EXPECT_TRUE(sContent.find("create(MirTypeKind::Integer, 32, 32, {}, \"my_int\", 2)") != std::string::npos);
    EXPECT_TRUE(sContent.find("create(MirTypeKind::FloatingPoint, 64, 64, {}, \"my_float\", 3)") != std::string::npos);
    EXPECT_TRUE(sContent.find("create(MirTypeKind::BindingToken, 0, 0, {}, \"my_token\", 4)") != std::string::npos);
}

// ============================================================================
// 4. Output Path Variations & Convenience Entry Point
// ============================================================================

TEST_F(CppMirTypeTableGeneratorTest, TestOutputPathVariationsAndConvenienceFunction)
{
    registerType("i64", DSL::Ast::TypeDef::TypeKind::Integer, 64, 64, 1);

    // Case 1: Explicit .h target path
    auto customHPath = m_testTempDir / "CustomTypeTable.h";
    EXPECT_TRUE(GenerateMirTypeTable(getDiagCollector(), getSymbolTable(), customHPath));
    EXPECT_TRUE(std::filesystem::exists(customHPath));
    EXPECT_TRUE(std::filesystem::exists(m_testTempDir / "CustomTypeTable.cpp"));

    // Case 2: Explicit .cpp target path
    auto customCppDir = m_testTempDir / "from_cpp";
    auto customCppPath = customCppDir / "TypesModule.cpp";
    EXPECT_TRUE(GenerateMirTypeTable(getDiagCollector(), getSymbolTable(), customCppPath));
    EXPECT_TRUE(std::filesystem::exists(customCppDir / "TypesModule.h"));
    EXPECT_TRUE(std::filesystem::exists(customCppPath));
}

TEST_F(CppMirTypeTableGeneratorTest, TestTimestampPreservationOnUnchangedGeneration)
{
    registerType("i16", DSL::Ast::TypeDef::TypeKind::Integer, 16, 16, 1);

    EXPECT_TRUE(GenerateMirTypeTable(getDiagCollector(), getSymbolTable(), m_testTempDir));

    auto hFile = m_testTempDir / "MirTypeTable.h";
    auto sFile = m_testTempDir / "MirTypeTable.cpp";

    auto pastTime = std::filesystem::last_write_time(hFile) - std::chrono::seconds(5);
    std::filesystem::last_write_time(hFile, pastTime);
    std::filesystem::last_write_time(sFile, pastTime);

    auto mtimeH1 = std::filesystem::last_write_time(hFile);
    auto mtimeS1 = std::filesystem::last_write_time(sFile);

    // Running again with identical symbols should preserve mtime of both files
    EXPECT_TRUE(GenerateMirTypeTable(getDiagCollector(), getSymbolTable(), m_testTempDir));
    auto mtimeH2 = std::filesystem::last_write_time(hFile);
    auto mtimeS2 = std::filesystem::last_write_time(sFile);

    EXPECT_EQ(mtimeH1, mtimeH2);
    EXPECT_EQ(mtimeS1, mtimeS2);
}

// ============================================================================
// 5. Negative and Edge Cases
// ============================================================================

TEST_F(CppMirTypeTableGeneratorTest, TestEmptySymbolTableGeneratesValidOutput)
{
    // Empty SymbolTable has 0 types
    CppMirTypeTableGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir);
    EXPECT_TRUE(generator.run());

    auto headerPath = m_testTempDir / "MirTypeTable.h";
    auto sourcePath = m_testTempDir / "MirTypeTable.cpp";

    EXPECT_TRUE(std::filesystem::exists(headerPath));
    EXPECT_TRUE(std::filesystem::exists(sourcePath));

    std::string hContent = readFileContent(headerPath);
    EXPECT_TRUE(hContent.find("constexpr size_t MachineTypeCount = 0;") != std::string::npos);
    EXPECT_TRUE(hContent.find("static constexpr size_t MachineDefinedTypeCount = 0;") != std::string::npos);
}

TEST_F(CppMirTypeTableGeneratorTest, TestOnlyPointerTypesGeneratesZeroPrimitives)
{
    registerType("ptr_a", DSL::Ast::TypeDef::TypeKind::Pointer, 64, 64, 1);
    registerType("ptr_b", DSL::Ast::TypeDef::TypeKind::Pointer, 32, 32, 2);

    CppMirTypeTableGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir);
    EXPECT_TRUE(generator.run());

    std::string hContent = readFileContent(m_testTempDir / "MirTypeTable.h");
    EXPECT_TRUE(hContent.find("constexpr size_t MachineTypeCount = 0;") != std::string::npos);
    EXPECT_TRUE(hContent.find("ptr_a =") == std::string::npos);
    EXPECT_TRUE(hContent.find("ptr_b =") == std::string::npos);
}

TEST_F(CppMirTypeTableGeneratorTest, TestIgnoresNonTypeSymbols)
{
    // Register an instruction symbol into the table
    Symbols::IrInstructionSymbol instSym{ .m_name = "DummyInst",
                                          .m_category = DSL::Ast::IrInstDef::IrInstCategory::System,
                                          .m_tier = DSL::Ast::IrInstDef::IrInstTier::HighLevel,
                                          .m_flags = DSL::Ast::IrInstDef::IrInstFlag::None };
    getSymbolTable()->declareSym(nullptr, SymbolType::IrInstruction, std::move(instSym), "DummyInst");

    CppMirTypeTableGenerator generator(getDiagCollector(), getSymbolTable(), m_testTempDir);
    EXPECT_TRUE(generator.run());

    std::string hContent = readFileContent(m_testTempDir / "MirTypeTable.h");
    EXPECT_TRUE(hContent.find("DummyInst") == std::string::npos);
}

TEST_F(CppMirTypeTableGeneratorTest, TestNullPointersAndEmptyPathFailValidation)
{
    CppMirTypeTableGenerator genNullCollector(nullptr, getSymbolTable(), m_testTempDir);
    EXPECT_FALSE(genNullCollector.run());

    CppMirTypeTableGenerator genNullTable(getDiagCollector(), nullptr, m_testTempDir);
    EXPECT_FALSE(genNullTable.run());

    CppMirTypeTableGenerator genEmptyPath(getDiagCollector(), getSymbolTable(), "");
    EXPECT_FALSE(genEmptyPath.run());
}
