#include "EzDslCliTestSuite.h"

#include <chrono>
#include <filesystem>

using namespace Cli;

/**
 * Integration fixture that runs the EzDsl CLI against the real EzMir DSL source files.
 */
class EzMirIntegrationTest : public EzDslCliTestSuiteAsGtest
{
  protected:
    std::filesystem::path m_typesPath;
    std::filesystem::path m_instructionsPath;

    // Resolves the bundled EzMir types and instructions source paths before each test.
    void SetUp() override
    {
        EzDslCliTestSuiteAsGtest::SetUp();
        m_typesPath = getEzMirTypesPath();
        m_instructionsPath = getEzMirInstructionsPath();
    }
};

// ============================================================================
// 1. Verification of EzMir DSL Source Files
// ============================================================================

TEST_F(EzMirIntegrationTest, EzMirSourceFilesExistAndAreNonEmpty)
{
    ASSERT_TRUE(std::filesystem::exists(m_typesPath)) << "Missing EzMir types specification: " << m_typesPath;
    ASSERT_TRUE(std::filesystem::exists(m_instructionsPath))
            << "Missing EzMir instructions specification: " << m_instructionsPath;

    EXPECT_GT(std::filesystem::file_size(m_typesPath), 0u);
    EXPECT_GT(std::filesystem::file_size(m_instructionsPath), 0u);
}

// ============================================================================
// 2. Syntactic & Semantic Validation of EzMir Specifications
// ============================================================================

TEST_F(EzMirIntegrationTest, CheckOnlyPassesOnEzMirTypes)
{
    CliOptions opts;
    opts.inputFilePath = m_typesPath.string();
    opts.outputPath = m_testTempDir.string();
    opts.checkOnly = true;

    auto result = runDriver(opts);
    EXPECT_TRUE(result.success) << "Failed check-only on " << m_typesPath << ": " << result.errorMessage;
    EXPECT_FALSE(std::filesystem::exists(m_testTempDir / "MirTypeTable.h"));
    EXPECT_FALSE(std::filesystem::exists(m_testTempDir / "MirTypeTable.cpp"));
}

// Verifies --check-only succeeds on the real EzMir instructions file without writing output.
TEST_F(EzMirIntegrationTest, CheckOnlyPassesOnEzMirInstructions)
{
    CliOptions opts;
    opts.inputFilePath = m_instructionsPath.string();
    opts.outputPath = m_testTempDir.string();
    opts.checkOnly = true;

    auto result = runDriver(opts);
    EXPECT_TRUE(result.success) << "Failed check-only on " << m_instructionsPath << ": " << result.errorMessage;
    EXPECT_FALSE(std::filesystem::exists(m_testTempDir / "MirInstructionSetDefs.h"));
}

// ============================================================================
// 3. Full Generation & Header/Source Content Verification for EzMir Types
// ============================================================================

TEST_F(EzMirIntegrationTest, GenerateAndVerifyEzMirTypeTable)
{
    CliOptions opts;
    opts.inputFilePath = m_typesPath.string();
    opts.outputPath = m_testTempDir.string();

    auto result = runDriver(opts);
    ASSERT_TRUE(result.success) << "Type table generation failed: " << result.errorMessage;

    auto headerPath = m_testTempDir / "MirTypeTable.h";
    auto sourcePath = m_testTempDir / "MirTypeTable.cpp";

    ASSERT_TRUE(std::filesystem::exists(headerPath));
    ASSERT_TRUE(std::filesystem::exists(sourcePath));

    std::string hContent = readFileContent(headerPath);
    std::string sContent = readFileContent(sourcePath);

    // --- Header File Verification ---
    // 1. Include Guards & Banner
    EXPECT_TRUE(hContent.find("#ifndef EZMIR_MIR_TYPE_TABLE_H") != std::string::npos);
    EXPECT_TRUE(hContent.find("#define EZMIR_MIR_TYPE_TABLE_H") != std::string::npos);
    EXPECT_TRUE(hContent.find("Auto-generated by EzDSL CppMirTypeTableGenerator") != std::string::npos);
    EXPECT_TRUE(hContent.find("#include \"Type/MirType.h\"") != std::string::npos);

    // 2. Compact ID Enum values matching EzMir types.tyf
    EXPECT_TRUE(hContent.find("enum class MirTypeCompactId : uint8_t") != std::string::npos);
    EXPECT_TRUE(hContent.find("Invalid = 0,") != std::string::npos);
    EXPECT_TRUE(hContent.find("_void = 1,") != std::string::npos);
    EXPECT_TRUE(hContent.find("__bindToken = 2,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i1 = 4,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i8 = 5,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i16 = 6,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i32 = 7,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i64 = 8,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i128 = 9,") != std::string::npos);
    EXPECT_TRUE(hContent.find("i256 = 10,") != std::string::npos);
    EXPECT_TRUE(hContent.find("f32 = 11,") != std::string::npos);
    EXPECT_TRUE(hContent.find("f64 = 12,") != std::string::npos);
    EXPECT_TRUE(hContent.find("f128 = 13,") != std::string::npos);
    EXPECT_TRUE(hContent.find("Custom = 255") != std::string::npos);

    // ptr is pointer type, must NOT have a compact ID
    EXPECT_TRUE(hContent.find("ptr =") == std::string::npos);

    // 3. MachineTypeCount (12 primitive types)
    EXPECT_TRUE(hContent.find("constexpr size_t MachineTypeCount = 12;") != std::string::npos);

    // 4. MirTypeTable Class Declarations & Accessor Methods
    EXPECT_TRUE(hContent.find("class MirTypeTable") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i1();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i8();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i16();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i32();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i64();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i128();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *i256();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *f32();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *f64();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *f128();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *_void();") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *__bindToken();") != std::string::npos);

    // 5. Member pointers & lifecycle
    EXPECT_TRUE(hContent.find("MirType *m_i32Type{ nullptr };") != std::string::npos);
    EXPECT_TRUE(hContent.find("MirType *m_f64Type{ nullptr };") != std::string::npos);
    EXPECT_TRUE(hContent.find("void initialize(size_t pointerBitWidth);") != std::string::npos);

    // --- Source File Verification ---
    EXPECT_TRUE(
            sContent.find(
                    "MirTypeTable::MirTypeTable(std::pmr::memory_resource *globalArena, size_t pointerBitWidth) :") !=
            std::string::npos);
    EXPECT_TRUE(sContent.find("m_compactIdToType.fill(nullptr);") != std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::i32() { return m_i32Type; }") != std::string::npos);
    EXPECT_TRUE(sContent.find("MirType *MirTypeTable::f64() { return m_f64Type; }") != std::string::npos);
    // Initialization checks
    EXPECT_TRUE(sContent.find("m_i1Type = create(MirTypeKind::Integer, 1, 1, {}, \"i1\", 4);") != std::string::npos);
    EXPECT_TRUE(sContent.find("m_i32Type = create(MirTypeKind::Integer, 32, 32, {}, \"i32\", 7);") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("m_i64Type = create(MirTypeKind::Integer, 64, 64, {}, \"i64\", 8);") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("m_f32Type = create(MirTypeKind::FloatingPoint, 32, 32, {}, \"f32\", 11);") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("m_f64Type = create(MirTypeKind::FloatingPoint, 64, 64, {}, \"f64\", 12);") !=
                std::string::npos);
    EXPECT_TRUE(sContent.find("m__voidType = create(MirTypeKind::Void, 0, 0, {}, \"_void\", 1);") != std::string::npos);
    EXPECT_TRUE(sContent.find("m___bindTokenType = create(MirTypeKind::BindingToken, 0, 0, {}, \"__bindToken\", 2);") !=
                std::string::npos);
}

// ============================================================================
// 4. Full Generation & Header Content Verification for EzMir Instructions
// ============================================================================

TEST_F(EzMirIntegrationTest, GenerateAndVerifyEzMirInstructionDefs)
{
    CliOptions opts;
    opts.inputFilePath = m_instructionsPath.string();
    opts.outputPath = m_testTempDir.string();

    auto result = runDriver(opts);
    ASSERT_TRUE(result.success) << "Instruction defs generation failed: " << result.errorMessage;

    auto headerPath = m_testTempDir / "MirInstructionSetDefs.h";
    ASSERT_TRUE(std::filesystem::exists(headerPath));

    std::string content = readFileContent(headerPath);

    // 1. Macros and wrappers
    EXPECT_TRUE(content.find("#ifdef INSTRUCTION") != std::string::npos);
    EXPECT_TRUE(content.find("#define OPERAND_CONSTRAINTS(...)") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(INVALID, T(HighLevel), MirCat_Invalid, OPERAND_CONSTRAINTS(), F(None))") !=
                std::string::npos);

    // 2. Data Movement instructions
    EXPECT_TRUE(content.find("INSTRUCTION(MOV,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(MOV_ADDR,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(PHI,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(PUSH_ARG,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(PUSH_RET,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(POP_ARG,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(END_ARG,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(POP_RET,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(SELECT,") != std::string::npos);

    // 3. Memory instructions
    EXPECT_TRUE(content.find("INSTRUCTION(LOAD,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(STORE,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(ALLOC,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(DALLOC,") != std::string::npos);

    // 4. Arithmetic & Bitwise instructions
    EXPECT_TRUE(content.find("INSTRUCTION(ADD,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(SUB,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(MUL,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(DIV,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(AND,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(OR,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(XOR,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(SHL,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(SHR,") != std::string::npos);

    // 5. Compare & Control Flow instructions
    EXPECT_TRUE(content.find("INSTRUCTION(CMP_EQ,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(CMP_NE,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(CMP_SLT,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(JMP,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(BR_COND,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(CALL,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(RET,") != std::string::npos);

    // 6. Casting & System instructions
    EXPECT_TRUE(content.find("INSTRUCTION(TRUNC,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(ZEXT,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(SEXT,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(BITCAST,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(NOP,") != std::string::npos);
    EXPECT_TRUE(content.find("INSTRUCTION(HALT,") != std::string::npos);

    // 7. Verify flags on critical instructions
    EXPECT_TRUE(content.find("F(VariadicArgs)") != std::string::npos);
    EXPECT_TRUE(content.find("F(IsTerminator)") != std::string::npos);
    EXPECT_TRUE(content.find("F(IsBranch)") != std::string::npos);
    EXPECT_TRUE(content.find("F(IsReturn)") != std::string::npos);
    EXPECT_TRUE(content.find("F(IsCall)") != std::string::npos);
    EXPECT_TRUE(content.find("F(ReadsMemory)") != std::string::npos);
    EXPECT_TRUE(content.find("F(WritesMemory)") != std::string::npos);
}

// ============================================================================
// 5. CMake Integration Contract Simulation
// ============================================================================

TEST_F(EzMirIntegrationTest, CMakeTypeTableGenerationContract)
{
    // Simulates EzDslGenerateTypeTable(TARGET EzMir INPUT types.tyf OUTPUT_DIR ...)
    std::string err;
    auto opts = parseArgs({ "-i", m_typesPath.string(), "-o", m_testTempDir.string(), "--emit-type-table" }, err);
    ASSERT_TRUE(opts.has_value()) << "CLI argument parsing failed: " << err;

    auto result1 = runDriver(*opts);
    EXPECT_TRUE(result1.success);
    EXPECT_EQ(result1.generatedFiles.size(), 2);

    auto hPath = m_testTempDir / "MirTypeTable.h";
    auto sPath = m_testTempDir / "MirTypeTable.cpp";

    auto mtimeH1 = std::filesystem::last_write_time(hPath);
    auto mtimeS1 = std::filesystem::last_write_time(sPath);

    // Re-run should preserve timestamps (incremental build contract)
    auto result2 = runDriver(*opts);
    EXPECT_TRUE(result2.success);
    EXPECT_EQ(result2.unchangedFiles.size(), 2);
    EXPECT_EQ(result2.generatedFiles.size(), 0);

    auto mtimeH2 = std::filesystem::last_write_time(hPath);
    auto mtimeS2 = std::filesystem::last_write_time(sPath);

    EXPECT_EQ(mtimeH1, mtimeH2);
    EXPECT_EQ(mtimeS1, mtimeS2);
}

// Simulates the CMake instruction-defs generation contract, including timestamp preservation on re-run.
TEST_F(EzMirIntegrationTest, CMakeInstructionDefsGenerationContract)
{
    // Simulates EzDslGenMirInstructions(TARGET EzMir INPUT instructions.irdf OUTPUT_DIR ...)
    std::string err;
    auto opts =
            parseArgs({ "-i", m_instructionsPath.string(), "-o", m_testTempDir.string(), "--emit-instructions" }, err);
    ASSERT_TRUE(opts.has_value()) << "CLI argument parsing failed: " << err;

    auto result1 = runDriver(*opts);
    EXPECT_TRUE(result1.success);
    EXPECT_EQ(result1.generatedFiles.size(), 1);

    auto hPath = m_testTempDir / "MirInstructionSetDefs.h";
    auto mtime1 = std::filesystem::last_write_time(hPath);

    // Re-run should preserve timestamps (incremental build contract)
    auto result2 = runDriver(*opts);
    EXPECT_TRUE(result2.success);
    EXPECT_EQ(result2.unchangedFiles.size(), 1);
    EXPECT_EQ(result2.generatedFiles.size(), 0);

    auto mtime2 = std::filesystem::last_write_time(hPath);
    EXPECT_EQ(mtime1, mtime2);
}

// ============================================================================
// 6. EzMir Metadata & Symbols Dump Inspection
// ============================================================================

TEST_F(EzMirIntegrationTest, DumpEzMirTypesJsonMetadata)
{
    CliOptions opts;
    opts.inputFilePath = m_typesPath.string();
    opts.outputPath = m_testTempDir.string();
    opts.dumpInfo = true;
    opts.dumpSymbols = true;
    opts.dryRun = true;
    opts.format = OutputFormat::Json;

    auto result = runDriver(opts);
    EXPECT_TRUE(result.success);
}

// Verifies dumping info and symbols for the real instructions file in JSON mode succeeds.
TEST_F(EzMirIntegrationTest, DumpEzMirInstructionsJsonMetadata)
{
    CliOptions opts;
    opts.inputFilePath = m_instructionsPath.string();
    opts.outputPath = m_testTempDir.string();
    opts.dumpInfo = true;
    opts.dumpSymbols = true;
    opts.dryRun = true;
    opts.format = OutputFormat::Json;

    auto result = runDriver(opts);
    EXPECT_TRUE(result.success);
}

// ============================================================================
// 7. CLI Subprocess End-to-End Execution
// ============================================================================

TEST_F(EzMirIntegrationTest, RunEzDslCliSubprocessOnEzMir)
{
    auto exe = findEzDslCliExe();
    if (exe.empty())
    {
        GTEST_SKIP() << "EzDslCli executable not found; skipping subprocess execution test.";
    }

    // 1. Process types.tyf
    std::string typesOutDir = (m_testTempDir / "proc_types").string();
    std::string stdOutTypes;
    int codeTypes = runCliProcess({ "-i", m_typesPath.string(), "-o", typesOutDir, "--emit-type-table" }, stdOutTypes);
    EXPECT_EQ(codeTypes, 0) << "CLI failed with output:\n" << stdOutTypes;
    EXPECT_TRUE(std::filesystem::exists(std::filesystem::path(typesOutDir) / "MirTypeTable.h"));
    EXPECT_TRUE(std::filesystem::exists(std::filesystem::path(typesOutDir) / "MirTypeTable.cpp"));

    // 2. Process instructions.irdf
    std::string instOutDir = (m_testTempDir / "proc_inst").string();
    std::string stdOutInst;
    int codeInst =
            runCliProcess({ "-i", m_instructionsPath.string(), "-o", instOutDir, "--emit-instructions" }, stdOutInst);
    EXPECT_EQ(codeInst, 0) << "CLI failed with output:\n" << stdOutInst;
    EXPECT_TRUE(std::filesystem::exists(std::filesystem::path(instOutDir) / "MirInstructionSetDefs.h"));
}
